// Stratum — the control on SPEC §11's legacy-seed refutation.
// Copyright 2026 the Stratum contributors. SPDX-License-Identifier: Apache-2.0
//
// SPEC §11 records that 270,000 candidate derivations of a NAMED noise's seed
// under `legacy_random_source` were scored against server output and that none
// survived. tools/analysis/legacy-seed-analyze.cpp is that scan, and it
// calibrates itself with `--plant`: a candidate planted inside the scanned
// space comes back rank 1, sole survivor, every column.
//
// THE PLANT CANNOT CLOSE THE ARGUMENT, and that is what this file is for. A
// plant synthesises its readings through the analyzer's OWN forward model, so
// a wrong model — a wrong persistence schedule, a wrong valueFactor, a missing
// second stack, a wrong cell-corner assumption, a wrong inversion of the
// gradient — is shared by the plant and the scan alike and the plant still
// returns rank 1. It shows the statistic is SENSITIVE. It does not show the
// model is RIGHT, and a refutation resting on it alone rests on nothing.
//
// SO SCORE A RULE THAT IS ALREADY KNOWN TO BE RIGHT. The probe worlds carry
// mirror dimensions — mod_single, mod_multi, mod_skip — that name the same
// noises without the legacy flag, generated by the same server start from the
// same seed. Their noises are therefore seeded by the modern derivation
// lib/src/noise_registry.cpp implements:
// XoroshiroPositionalFactory(worldSeed).fromHashOf(id), then
// NormalNoise::create. Put THAT through the identical readback, the identical
// band and the identical columns, and if it comes back whole then a correct
// named-noise rule is recoverable through this apparatus, and the legacy rule
// is absent from the searched space rather than invisible to the tool.
//
// Two things are asserted, and the second is the one that buys the plant's
// remaining ground:
//
//   * the modern rule recovers every column of every mirror dimension, and
//   * it does so EXACTLY through the same `quantise` inversion the plant
//     relies on — the model value put back through the block quantisation
//     lands on the server's own reading as a double, not near it.
//
// The second is not decoration. Breaking the inversion the way it was once
// actually broken — `floor(t - 0.5)` for `ceil(t) - 1`, which made the plant
// score 51% — leaves the FIRST assertion at every column and shows up only in
// the second, at about half of them. A band one terrain block wide cannot see
// it. The analyzer carries a third arm this file has no use for, comparing
// its own hand-rolled forward model and `valueFactor` against the library's
// bit for bit; here the library IS the model, so there is nothing to compare.
//
// And the mirror runs the other way too: the same rule on the legacy
// dimensions of the same world must sit at that dimension's measured null. A
// rule that won because of the readback rather than because of the seeding
// would score alike on both sides.
//
// THE NEGATIVE CONTROL closes that argument properly, and the legacy mirror
// alone does not. The legacy mirror varies the FLAG and the seeding together,
// so it cannot separate "the seeding is what is being recovered" from "the
// flag changes something else". Scoring the same modern derivation at
// worldSeed + 1 against the SAME mod_* dimensions varies one thing only. It
// must fall to the null; if it did not, the recovery above would be the
// readback accepting anything.
//
// TWO CAVEATS, and the second is the one this apparatus cannot discharge.
//
//   1. It does not widen the searched space. A control on a modern rule says
//      nothing about whether the legacy rule uses a stack shape the scan
//      never enumerates, which remains the likeliest place for it to hide.
//
//   2. Everything validated here is validated on the MODERN dimensions. The
//      readback, the coordinate convention, the band and the `quantise`
//      inversion are shown correct where the legacy flag is absent, so the
//      step from "no survivor" to "absent from the space rather than
//      invisible to the tool" ASSUMES the flag changes the seeding and
//      nothing else in the terrain pipeline. Nothing here measures that
//      directly, and nothing short of the pipeline itself could.
//
//      What this file does instead is bound the assumption. If the flag also
//      moved the gradient, the output scale, the cell spacing or the sampling
//      coordinates, the legacy readback would not have the same SPREAD or the
//      same NEIGHBOUR-TO-NEIGHBOUR structure as its modern mirror. Both are
//      measured below, per noise shape, at lag 4 — the probe's own column
//      spacing, where a change in cell size or frequency bites hardest. It is
//      a refutable statement rather than a proof, and it is what replaced a
//      bare assumption. See SPEC §11.
//
// AND WHAT THE CONTROL DOES NOT REACH, inside the apparatus rather than
// outside it: `blocksFor` under `Generator::Lcg` — Java `Random` driving
// `PerlinNoise::fromRandom`, which half of the 270,000 candidates use — is
// exercised by neither the control nor this file. Both run Xoroshiro128++
// only, because the modern derivation is the rule known to be right. That
// path is validated against the server in
// tests/conformance/vanilla_legacy_blended_test.cpp, where
// `BlendedNoise::legacyFromWorldSeed` is `JavaRandom{worldSeed}` handed
// straight into the same `PerlinNoise::fromRandom`.
//
// THE NULL IS PER-DIMENSION. A column counts as agreement within half a
// quantum, a quantum being one block of terrain — 2 / height / (K * scale) —
// so the coarser copies of the same noise accept a wider band and ANY wrong
// rule scores higher there for no other reason. The ceilings below are
// per-dimension and come from the scan's own measured null (its `--scan` line
// prints mean and max for each), not from one number quoted across
// configurations. That mistake is how a 16% score once read as an outlier
// against 0-5% siblings when it was its own dimension's null; see SPEC §11.
//
// The fixtures come from tools/analysis/legacy-seed-probe.sh and are
// Mojang-derived, so they are never committed (SPEC §12). Without them this
// SKIPs — and a skip here is not a pass: Catch2 exits 4 when every selected
// case skips, and ctest reads that as a skip rather than as success only
// because catch_discover_tests sets SKIP_RETURN_CODE 4 (Catch.cmake:219).
// Run the binary by hand and the shell reports 4, not 0.
//
// It skips on BOTH seeds or on neither. Scoring one world and reporting a
// pass is the failure mode this file exists to refuse: one world seed
// agreeing with an RNG-driven derivation is evidence that it agrees once.
#include <stratum/chunk/chunk.hpp>
#include <stratum/nbt/reader.hpp>
#include <stratum/noise/perlin.hpp>
#include <stratum/region/region_file.hpp>
#include <stratum/rng/xoroshiro128.hpp>

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <array>
#include <bit>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <span>
#include <string>
#include <vector>

namespace {

// Must match tools/analysis/density-probe.sh and legacy-seed-probe.sh.
constexpr double kK = 0.35;
constexpr int kMinY = -64;
constexpr int kHeight = 384;

/// The noises legacy-seed-probe.sh ships in its `<spec>.noises.json` sidecar,
/// repeated here because a test that reads its own expectations out of the
/// fixture cannot fail when the fixture changes.
struct Noise {
    const char* id;
    int firstOctave;
    std::array<double, 3> amplitudes;
    std::size_t amplitudeCount;
};

constexpr Noise kNa{"stratum:na", -3, {1.0, 0.0, 0.0}, 1};
constexpr Noise kNmulti{"stratum:nmulti", -5, {1.0, 1.0, 1.0}, 3};
constexpr Noise kNskip{"stratum:nskip", -5, {1.0, 0.0, 1.0}, 3};
constexpr Noise kNb{"stratum:nb", -3, {1.0, 0.0, 0.0}, 1};

struct Dimension {
    const char* name;
    bool legacy;
    Noise noise;
    double scale;
    /// Only meaningful for a legacy dimension: the largest share of columns
    /// the modern rule may reach there before it stops looking like this
    /// dimension's null.
    ///
    /// THE DENOMINATORS MATCH, which they did not before. These ceilings are
    /// fractions of the ~2304 columns this file scores, so they are justified
    /// against what the modern rule ACTUALLY reaches over 2304 columns — the
    /// numbers below, measured here on both seeds — and not against the
    /// scan's null, which is reported per 128 subsampled columns and cannot
    /// be compared to a 2304-column count without first being turned into a
    /// rate.
    ///
    ///   scale 2      12-23 of 2304 (0.52-1.00%), ceiling 0.03 = 69/2304
    ///   scale 0.5    58-61 of 2304 (2.52-2.65%), ceiling 0.08 = 184/2304
    ///   scale 0.125  246-262 of 2304 (10.68-11.37%), ceiling 0.25 = 576/2304
    ///
    /// Each ceiling is 2.2 to 3.0 times the largest count measured at that
    /// scale — headroom for a different seed, not for a signal. As a rate the
    /// scan agrees: its null MEAN at seed 42 is 0.61-0.84% at scale 2, 2.55%
    /// at 0.5 and 10.15% at 0.125, which brackets the measured counts above.
    /// The null MAX (7-9/128, 18/128, 47/128 — 5.5%, 14%, 37%) is deliberately
    /// NOT the reference: it is the best of 270,000 wrong candidates, so
    /// sitting under it argues the wrong way. A ceiling has to be near the
    /// null's CENTRE to mean anything.
    double nullCeiling;
};

constexpr std::array<Dimension, 9> kDimensions{{
    {"leg_single", true, kNa, 2.0, 0.03},
    {"mod_single", false, kNa, 2.0, 0.0},
    {"leg_twin", true, kNb, 2.0, 0.03},
    {"leg_multi", true, kNmulti, 2.0, 0.03},
    {"mod_multi", false, kNmulti, 2.0, 0.0},
    {"leg_skip", true, kNskip, 2.0, 0.03},
    {"mod_skip", false, kNskip, 2.0, 0.0},
    {"leg_skip_q4", true, kNskip, 0.5, 0.08},
    {"leg_skip_q16", true, kNskip, 0.125, 0.25},
}};

/// The seeds legacy-seed-probe.sh was run at. Two, because one world seed
/// agreeing with an RNG-driven derivation is evidence that it agrees once.
constexpr std::array<std::int64_t, 2> kSeeds{42, 31337};

struct Column {
    double x = 0.0;
    double z = 0.0;
    double value = 0.0;
};

[[nodiscard]] double quantum(double scale) {
    return 2.0 / static_cast<double>(kHeight) / (kK * scale);
}

[[nodiscard]] std::filesystem::path probeRoot(std::int64_t seed) {
    return std::filesystem::path{STRATUM_FIXTURES_DIR} / "1.21.11" / "probes" /
           ("legseed_s" + std::to_string(seed));
}

/// Every cell-corner column of one probe region, inverted into a reading of
/// the noise at (x, 0, z). Columns with no block belong to chunks the server
/// left unbuilt around the forceloaded square; a column whose terrain reached
/// the floor or the ceiling ran past the gradient's range and its height no
/// longer carries the value. Both are dropped rather than counted, which would
/// let any candidate that also saturates agree for free.
[[nodiscard]] std::vector<Column> readColumns(const std::filesystem::path& region, double scale) {
    std::vector<Column> columns;
    const stratum::region::RegionFile file = stratum::region::RegionFile::open(region);
    for (std::int32_t chunkZ = 0; chunkZ < 32; ++chunkZ) {
        for (std::int32_t chunkX = 0; chunkX < 32; ++chunkX) {
            if (!file.hasChunk(chunkX, chunkZ)) {
                continue;
            }
            const stratum::chunk::Chunk decoded = stratum::chunk::Chunk::decode(
                stratum::nbt::read(file.readChunk(chunkX, chunkZ)).root);
            for (int localZ = 0; localZ < 16; ++localZ) {
                for (int localX = 0; localX < 16; ++localX) {
                    const std::int32_t x = (chunkX * 16) + localX;
                    const std::int32_t z = (chunkZ * 16) + localZ;
                    if ((x % 4) != 0 || (z % 4) != 0) {
                        continue;
                    }
                    int surface = kMinY - 1;
                    for (int y = kMinY + kHeight - 1; y >= kMinY; --y) {
                        const stratum::chunk::BlockState* block =
                            decoded.blockAt(localX, y, localZ);
                        if (block != nullptr && block->name != "minecraft:air") {
                            surface = y;
                            break;
                        }
                    }
                    if (surface <= kMinY || surface >= kMinY + kHeight - 1) {
                        continue;
                    }
                    const double gradient =
                        1.0 - (2.0 * ((surface + 0.5) - kMinY) / static_cast<double>(kHeight));
                    columns.push_back(
                        {static_cast<double>(x), static_cast<double>(z), -gradient / (kK * scale)});
                }
            }
        }
    }
    return columns;
}

/// A value put through the quantisation the server's terrain imposes, which is
/// the step `--plant` depends on: the server places a block wherever
/// K*scale*f + g(y) is positive, so the crossing sits at
/// min_y + height * (1 + K*scale*f) / 2 and the surface is the highest whole y
/// strictly below it.
[[nodiscard]] double quantise(double value, double scale) {
    const double crossing = (((1.0 + (value * kK * scale)) * kHeight / 2.0) + kMinY);
    const auto surface = static_cast<int>(std::ceil(crossing)) - 1;
    const double back = 1.0 - (2.0 * ((surface + 0.5) - kMinY) / static_cast<double>(kHeight));
    return -back / (kK * scale);
}

/// lib/src/noise_registry.cpp's modern derivation, spelled the way that file
/// spells it: one positional fork of the world seed, the noise's identifier
/// hashed into it, and NormalNoise on top.
/// Which of the three SHAPES the probe carries a dimension is an instance of.
/// `stratum:na` and `stratum:nb` differ only in their identifier, so they are
/// the same shape reached through two different seeds; the q4 and q16
/// dimensions are the skip shape read back at a coarser output scale.
enum class Shape : std::size_t { Single = 0, Multi = 1, Skip = 2 };
constexpr std::size_t kShapeCount = 3;
constexpr std::array<const char*, kShapeCount> kShapeNames{"1-octave", "3-octave", "skip"};

[[nodiscard]] Shape shapeOf(const Noise& noise) {
    if (noise.amplitudeCount == 1) {
        return Shape::Single;
    }
    // > 0.0 rather than != 0.0: the amplitudes are 0.0 or 1.0 and the project
    // builds with -Wfloat-equal.
    return noise.amplitudes[1] > 0.0 ? Shape::Multi : Shape::Skip;
}

/// One dimension's readback described without reference to any candidate
/// rule: how wide the values spread, and how strongly a column agrees with
/// its neighbour 4 blocks away. This is the measurement that bounds caveat 2
/// in the header — a legacy dimension whose pipeline differed from its modern
/// mirror in more than the seeding would not match its mirror here.
struct Profile {
    double sd = 0.0;
    double lag4 = 0.0;
    std::size_t lagPairs = 0;
};

/// Flat index into the lattice below, each operand widened before the
/// multiply rather than after it — the same spelling
/// tools/analysis/legacy-seed-analyze.cpp uses, and for the same reason.
[[nodiscard]] std::size_t latticeIndex(int gx, int gz, int side) {
    return (static_cast<std::size_t>(gz) * static_cast<std::size_t>(side)) +
           static_cast<std::size_t>(gx);
}

[[nodiscard]] Profile profileOf(const std::vector<Column>& columns) {
    Profile profile;
    if (columns.empty()) {
        return profile;
    }
    double sum = 0.0;
    for (const Column& column : columns) {
        sum += column.value;
    }
    const double mean = sum / static_cast<double>(columns.size());
    double variance = 0.0;
    for (const Column& column : columns) {
        const double d = column.value - mean;
        variance += d * d;
    }
    variance /= static_cast<double>(columns.size());
    profile.sd = std::sqrt(variance);

    // A dense lattice rather than a map: the probe reads every 4th block of a
    // 512-block region, so the grid is 128x128.
    constexpr int kStep = 4;
    constexpr int kSide = 512 / kStep;
    std::vector<double> grid(static_cast<std::size_t>(kSide) * kSide, 0.0);
    std::vector<char> present(static_cast<std::size_t>(kSide) * kSide, 0);
    for (const Column& column : columns) {
        const int gx = static_cast<int>(column.x) / kStep;
        const int gz = static_cast<int>(column.z) / kStep;
        if (gx < 0 || gx >= kSide || gz < 0 || gz >= kSide) {
            continue;
        }
        const std::size_t index = latticeIndex(gx, gz, kSide);
        grid[index] = column.value;
        present[index] = 1;
    }

    double covariance = 0.0;
    std::size_t pairs = 0;
    for (int gz = 0; gz < kSide; ++gz) {
        for (int gx = 0; gx < kSide; ++gx) {
            const std::size_t here = latticeIndex(gx, gz, kSide);
            if (present[here] == 0) {
                continue;
            }
            const double a = grid[here] - mean;
            if (gx + 1 < kSide) {
                const std::size_t east = latticeIndex(gx + 1, gz, kSide);
                if (present[east] != 0) {
                    covariance += a * (grid[east] - mean);
                    ++pairs;
                }
            }
            if (gz + 1 < kSide) {
                const std::size_t south = latticeIndex(gx, gz + 1, kSide);
                if (present[south] != 0) {
                    covariance += a * (grid[south] - mean);
                    ++pairs;
                }
            }
        }
    }
    profile.lagPairs = pairs;
    if (pairs != 0 && variance > 0.0) {
        profile.lag4 = covariance / (static_cast<double>(pairs) * variance);
    }
    return profile;
}

/// Running mean of one statistic over the instances of one shape on one side
/// of the mirror.
struct Tally {
    double total = 0.0;
    std::size_t count = 0;

    void add(double value) {
        total += value;
        ++count;
    }

    [[nodiscard]] double mean() const {
        return count == 0 ? 0.0 : total / static_cast<double>(count);
    }
};

[[nodiscard]] stratum::noise::NormalNoise modernNoise(const Noise& noise, std::int64_t worldSeed) {
    const stratum::rng::XoroshiroPositionalFactory factory{worldSeed};
    stratum::rng::Xoroshiro128PlusPlus random = factory.fromHashOf(noise.id);
    return stratum::noise::NormalNoise::create(
        random, noise.firstOctave,
        std::span<const double>{noise.amplitudes.data(), noise.amplitudeCount});
}

} // namespace

TEST_CASE("the legacy-seed scan recovers a named-noise rule that is known to be right",
          "[conformance][legacy][seed][control]") {
    // BOTH SEEDS OR NEITHER, decided before any scoring. Silently dropping to
    // one world and reporting a pass is exactly the degradation this file is
    // supposed to rule out, so a partial fixture set is a SKIP that names the
    // world that is missing — not a green run over half the evidence.
    std::size_t present = 0;
    std::string missing;
    for (const std::int64_t seed : kSeeds) {
        if (std::filesystem::is_directory(probeRoot(seed))) {
            ++present;
        } else {
            missing += (missing.empty() ? "" : ", ") + std::to_string(seed);
        }
    }
    if (present < kSeeds.size()) {
        SKIP("legseed probe world(s) for seed(s) "
             << missing << " missing under "
             << (std::filesystem::path{STRATUM_FIXTURES_DIR} / "1.21.11" / "probes")
             << "; this case requires all " << kSeeds.size()
             << ", because one world seed agreeing with an RNG-driven derivation is "
                "evidence that it agrees once. Regenerate with: "
                "tools/analysis/legacy-seed-probe.sh --accept-eula <seed>");
    }

    std::size_t worlds = 0;
    std::size_t mirrorColumns = 0;
    std::size_t mirrorRecovered = 0;
    std::size_t mirrorExact = 0;
    std::size_t mirrorWrongSeed = 0;

    // Distribution and lag-4 structure, pooled per shape and per side of the
    // mirror, so legacy and modern can be compared shape for shape.
    std::array<Tally, kShapeCount> legacySd;
    std::array<Tally, kShapeCount> modernSd;
    std::array<Tally, kShapeCount> legacyLag;
    std::array<Tally, kShapeCount> modernLag;
    double widestSingleLag = -2.0;
    double narrowestOtherLag = 2.0;
    double lowestSd = 2.0;
    double highestSd = -1.0;

    for (const std::int64_t seed : kSeeds) {
        const std::filesystem::path root = probeRoot(seed);
        REQUIRE(std::filesystem::is_directory(root));
        ++worlds;
        for (const Dimension& dimension : kDimensions) {
            const std::filesystem::path region = root / dimension.name / "r.0.0.mca";
            REQUIRE(std::filesystem::is_regular_file(region));

            const std::vector<Column> columns = readColumns(region, dimension.scale);
            // The probe forceloads 8x8 chunks, which is 32x32 cell corners;
            // the server generates a wider square around them. Anything much
            // smaller means the world did not finish, and a shrunken
            // denominator is how a partial world passes.
            REQUIRE(columns.size() >= 2048U);

            // The readback's own shape, before any rule is scored against it.
            const Profile profile = profileOf(columns);
            const auto shape = static_cast<std::size_t>(shapeOf(dimension.noise));
            (dimension.legacy ? legacySd : modernSd)[shape].add(profile.sd);
            (dimension.legacy ? legacyLag : modernLag)[shape].add(profile.lag4);
            lowestSd = std::min(lowestSd, profile.sd);
            highestSd = std::max(highestSd, profile.sd);
            if (shapeOf(dimension.noise) == Shape::Single) {
                widestSingleLag = std::max(widestSingleLag, profile.lag4);
            } else {
                narrowestOtherLag = std::min(narrowestOtherLag, profile.lag4);
            }
            INFO("seed " << seed << " dimension " << dimension.name << " shape "
                         << kShapeNames[shape] << ": sd " << profile.sd << ", lag-4 "
                         << profile.lag4 << " over " << profile.lagPairs << " pairs");
            // Every column pairs with its east and south neighbour except at
            // the far edges of the 48x48 forceloaded lattice, so the pair
            // count is a second guard on the world having finished.
            CHECK(profile.lagPairs >= columns.size());

            const double band = 0.5 * quantum(dimension.scale);
            const stratum::noise::NormalNoise reference = modernNoise(dimension.noise, seed);
            // THE NEGATIVE CONTROL. One thing varied — the world seed — with
            // the flag, the dimension, the readback and the band held fixed.
            const stratum::noise::NormalNoise wrongSeed = modernNoise(dimension.noise, seed + 1);

            std::size_t agreed = 0;
            std::size_t exact = 0;
            std::size_t wrong = 0;
            for (const Column& column : columns) {
                const double ours = reference.sample(column.x, 0.0, column.z);
                if (std::abs(ours - column.value) <= band + 1e-12) {
                    ++agreed;
                }
                if (std::abs(wrongSeed.sample(column.x, 0.0, column.z) - column.value) <=
                    band + 1e-12) {
                    ++wrong;
                }
                // Compared as bits, not as doubles: the project builds with
                // -Wfloat-equal, and this equality is the deliberate kind —
                // the two must be the SAME double, and `back` can never be
                // zero here, so there is no signed-zero case to fall foul of.
                if (std::bit_cast<std::uint64_t>(quantise(ours, dimension.scale)) ==
                    std::bit_cast<std::uint64_t>(column.value)) {
                    ++exact;
                }
            }

            INFO("seed " << seed << " dimension " << dimension.name << " band " << band
                         << ": modern rule agrees on " << agreed << " and quantises exactly on "
                         << exact << " of " << columns.size() << "; at worldSeed + 1 it agrees on "
                         << wrong);

            // At worldSeed + 1 the rule has to fall to this dimension's null
            // wherever it is scored — on the mirror dimensions this is the
            // refutation of "the readback accepts anything", and on the
            // legacy ones it is one more wrong candidate.
            CHECK(static_cast<double>(wrong) <= (dimension.legacy ? dimension.nullCeiling : 0.03) *
                                                    static_cast<double>(columns.size()));

            if (dimension.legacy) {
                // The other half of the mirror. Same rule, same readback, same
                // world, same server start — and on a dimension that declares
                // the flag it must land at that dimension's own null. This is
                // what separates "the derivation is right" from "the readback
                // accepts anything".
                CHECK(static_cast<double>(agreed) <=
                      dimension.nullCeiling * static_cast<double>(columns.size()));
                continue;
            }

            // Every column, to the limit of what a terrain-height readback can
            // resolve...
            CHECK(agreed == columns.size());
            // ...and exactly, through the same inversion `--plant` uses, which
            // is the step the plant could never test on its own.
            CHECK(exact == columns.size());

            mirrorColumns += columns.size();
            mirrorRecovered += agreed;
            mirrorExact += exact;
            mirrorWrongSeed += wrong;
        }
    }

    // The presence check above already skipped a partial fixture set; this is
    // the invariant it was protecting, stated where it can be read.
    REQUIRE(worlds == kSeeds.size());

    // Stated as counts, so a world that half-generated cannot pass by
    // shrinking its denominator.
    CHECK(mirrorRecovered == mirrorColumns);
    CHECK(mirrorExact == mirrorColumns);
    // ...and the same derivation one seed away does not.
    INFO("at worldSeed + 1 the modern rule reaches " << mirrorWrongSeed << " of " << mirrorColumns
                                                     << " mirror columns");
    CHECK(static_cast<double>(mirrorWrongSeed) <= 0.03 * static_cast<double>(mirrorColumns));

    // --- caveat 2, bounded ---------------------------------------------------
    //
    // Legacy and modern readbacks compared shape for shape. The tolerances are
    // roughly three times the largest difference measured over both seeds, so
    // they are headroom for another world rather than for a different
    // pipeline; the measured figures are in SPEC §11.
    for (std::size_t shape = 0; shape < kShapeCount; ++shape) {
        INFO("shape " << kShapeNames[shape] << ": sd legacy " << legacySd[shape].mean()
                      << " vs modern " << modernSd[shape].mean() << "; lag-4 legacy "
                      << legacyLag[shape].mean() << " vs modern " << modernLag[shape].mean());
        REQUIRE(legacySd[shape].count > 0);
        REQUIRE(modernSd[shape].count > 0);
        CHECK(std::abs(legacySd[shape].mean() - modernSd[shape].mean()) <= 0.06);
        CHECK(std::abs(legacyLag[shape].mean() - modernLag[shape].mean()) <= 0.15);
    }

    // The statistic has to be able to SEE a difference in structure, or
    // matching on it would mean nothing. The three shapes separate far more
    // strongly than the two sides of the mirror do: every 1-octave instance
    // sits well below every 3-octave and skip instance, legacy and modern
    // alike.
    INFO("widest 1-octave lag-4 " << widestSingleLag << " vs narrowest 3-octave/skip "
                                  << narrowestOtherLag);
    CHECK(narrowestOtherLag - widestSingleLag >= 0.30);

    // And every dimension's spread lands in one interval, which it would not
    // if the flag moved the output scale or the gradient.
    INFO("sd over all dimensions and seeds: " << lowestSd << " to " << highestSd);
    CHECK(lowestSd >= 0.20);
    CHECK(highestSd <= 0.40);
}
