// Stratum — the per-world pipeline freeze.
// Copyright 2026 the Stratum contributors. SPDX-License-Identifier: Apache-2.0
//
// SPEC §6: at world creation the fully-resolved pipeline is serialised into
// the world's folder, and generation reads from that copy and never from the
// live preset registry. The reason is chunk seams. A world generated over
// months is generated by whatever engine and whatever datapack happened to
// be installed each day; without a frozen pipeline, editing a preset or
// upgrading the engine silently changes the terrain of every chunk generated
// after it, and the join between old and new is visible in the world
// forever.
//
// Three properties this file exists to hold, from SPEC §5.6 and §6:
//
//   * **Byte-identical.** Freezing the same pipeline twice produces the same
//     bytes, on every platform. That is why the format is binary and
//     little-endian with explicit widths, and why every double is written as
//     its bit pattern rather than as text: a `printf` of a double is a
//     platform's opinion, and this needs a fact.
//   * **Self-describing.** Every blob carries the pipeline engine version,
//     the schema pin it was built against, and a hash of its own contents.
//   * **Loud when it cannot be honoured.** A blob from an engine version
//     this build cannot reproduce is refused, by name, rather than generated
//     from on a best-effort basis. Silent best-effort is what §6 forbids.
//
// WHAT IS NOT IN IT. The world seed. A seed is world metadata rather than
// pipeline: the same frozen pipeline generates different worlds for
// different seeds, and the server already stores the seed itself.

#pragma once

#include <stratum/data/resource_location.hpp>
#include <stratum/density/graph.hpp>
#include <stratum/density/noise_registry.hpp>
#include <stratum/hash/md5.hpp>
#include <stratum/settings/noise_settings.hpp>

#include <cstddef>
#include <cstdint>
#include <map>
#include <span>
#include <stdexcept>
#include <string>
#include <vector>

namespace stratum::freeze {

/// Raised when a blob cannot be written or cannot be honoured. The message
/// always says which of the two it is and why, because "could not load
/// world" is not something anyone can act on.
class FreezeError : public std::runtime_error {
public:
    using std::runtime_error::runtime_error;
};

/// Everything a world needs in order to generate, resolved and detached from
/// the pack it came from. This is the thing that gets frozen.
struct Pipeline {
    density::Graph graph;
    /// The `worldgen/noise` entries the graph names, as parameters rather
    /// than as built noises: a built noise is a function of the seed, and
    /// the seed is not part of the pipeline.
    std::map<data::ResourceLocation, density::NoiseParameters> noises;
    std::map<data::ResourceLocation, settings::NoiseSettings> settings;
};

/// What a blob says about itself, readable without decoding the rest of it.
struct Provenance {
    std::uint32_t blobFormat = 0;
    std::uint32_t pipelineEngineVersion = 0;
    std::string minecraftVersion;
    std::int32_t packFormatMajor = 0;
    std::int32_t packFormatMinor = 0;
    /// Over the payload only, so that it can be checked before anything in
    /// the payload is believed.
    hash::Md5Digest contentHash{};

    [[nodiscard]] bool operator==(const Provenance& other) const = default;
};

/// The format this build writes. Distinct from the *engine* version: the
/// container can change shape without the generated world changing, and a
/// world does not need regenerating because a field moved.
///
/// 2 since a node's noise field became a union: it is written as a tag byte
/// naming which of the two spellings was used, where format 1 wrote a
/// present/absent flag. The two are byte-compatible for a blob with no
/// inline noise in it, which is exactly why the number has to change — a
/// format-1 reader would take the new tag for the old flag and read the
/// parameters as an identifier.
inline constexpr std::uint32_t kBlobFormat = 2;

/// Serialises @p pipeline. Deterministic: the same pipeline gives the same
/// bytes, here and on any other platform.
[[nodiscard]] std::vector<std::byte> write(const Pipeline& pipeline);

/// Reads the header alone, which is what a caller wants when deciding
/// whether a world can be opened at all. Throws FreezeError if the bytes are
/// not a blob this build recognises.
[[nodiscard]] Provenance inspect(std::span<const std::byte> blob);

/// Reads a whole blob. Refuses, naming what is wrong, if the container
/// format or the pipeline engine version is not one this build reproduces,
/// if the content hash does not match, or if the payload is malformed.
///
/// The engine version check is the load-bearing one (SPEC §6): a build that
/// generates differently from the one that wrote the blob must not open the
/// world at all, because the alternative is a seam.
[[nodiscard]] Pipeline read(std::span<const std::byte> blob);

} // namespace stratum::freeze
