// Stratum — the per-world pipeline freeze.
// Copyright 2026 the Stratum contributors. SPDX-License-Identifier: Apache-2.0
//
// SPEC §6: at world creation the fully-resolved pipeline is serialised into
// the world's folder, and generation reads from that copy and never from the
// live preset registry. The reason is chunk seams. A world generated over
// months is generated by whatever engine and whatever datapack happened to
// be installed each day; without a frozen pipeline, editing a preset or
// upgrading the engine silently changes the terrain of every chunk generated
// after it, and the join between old and new is visible in the world
// forever.
//
// Three properties this file exists to hold, from SPEC §5.6 and §6:
//
//   * **Byte-identical.** Freezing the same pipeline twice produces the same
//     bytes, on every platform. That is why the format is binary and
//     little-endian with explicit widths, and why every double is written as
//     its bit pattern rather than as text: a `printf` of a double is a
//     platform's opinion, and this needs a fact.
//   * **Self-describing.** Every blob carries the pipeline engine version,
//     the schema pin it was built against, and a hash of its own contents.
//   * **Loud when it cannot be honoured.** A blob from an engine version
//     this build cannot reproduce is refused, by name, rather than generated
//     from on a best-effort basis. Silent best-effort is what §6 forbids.
//
// WHAT IS NOT IN IT. The world seed. A seed is world metadata rather than
// pipeline: the same frozen pipeline generates different worlds for
// different seeds, and the server already stores the seed itself.

#pragma once

#include <stratum/biome/parameter_list.hpp>
#include <stratum/biome/temperature_table.hpp>
#include <stratum/data/pack.hpp>
#include <stratum/data/resource_location.hpp>
#include <stratum/density/graph.hpp>
#include <stratum/density/noise_registry.hpp>
#include <stratum/hash/md5.hpp>
#include <stratum/settings/noise_settings.hpp>

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <map>
#include <span>
#include <stdexcept>
#include <string>
#include <vector>

namespace stratum::freeze {

/// Raised when a blob cannot be written or cannot be honoured. The message
/// always says which of the two it is and why, because "could not load
/// world" is not something anyone can act on.
class FreezeError : public std::runtime_error {
public:
    using std::runtime_error::runtime_error;
};

/// Everything a world needs in order to generate, resolved and detached from
/// the pack it came from. This is the thing that gets frozen.
struct Pipeline {
    density::Graph graph;
    /// `worldgen/noise` entries, as parameters rather than as built noises: a
    /// built noise is a function of the seed, and the seed is not part of the
    /// pipeline. `resolve` freezes every noise the pack defines, not only
    /// the ones the graph names — surface rules sample noises of their own.
    std::map<data::ResourceLocation, density::NoiseParameters> noises;
    std::map<data::ResourceLocation, settings::NoiseSettings> settings;
    /// Multi-noise biome parameter lists, by list id (`minecraft:overworld`).
    /// Not in a data pack as data — vanilla compiles them in and only its
    /// data generator dumps them — so they have to travel with the world.
    std::map<data::ResourceLocation, biome::ParameterList> biomeParameters;
    /// Every biome's declared temperature, which surface rules read.
    biome::TemperatureTable biomeTemperatures;
};

/// Everything a world generates from, resolved out of @p pack (a `worldgen/`
/// tree) and the biome parameter lists under @p biomeParametersDir
/// (`<namespace>/<id>.json`, as `tools/fetch-vanilla` dumps them). The one
/// place a frozen pipeline is assembled, so every caller freezes the same
/// things. Throws whatever the loaders throw, naming the entry.
[[nodiscard]] Pipeline resolve(const data::Pack& pack,
                               const std::filesystem::path& biomeParametersDir);

/// What a blob says about itself, readable without decoding the rest of it.
struct Provenance {
    std::uint32_t blobFormat = 0;
    std::uint32_t pipelineEngineVersion = 0;
    std::string minecraftVersion;
    std::int32_t packFormatMajor = 0;
    std::int32_t packFormatMinor = 0;
    /// Over the payload only, so that it can be checked before anything in
    /// the payload is believed.
    hash::Md5Digest contentHash{};

    [[nodiscard]] bool operator==(const Provenance& other) const = default;
};

/// The format this build writes. Distinct from the *engine* version: the
/// container can change shape without the generated world changing, and a
/// world does not need regenerating because a field moved.
///
/// 2 since a node's noise field became a union: it is written as a tag byte
/// naming which of the two spellings was used, where format 1 wrote a
/// present/absent flag.
///
/// 3 since the blob carries the biome parameter lists and biome temperatures
/// generation has needed since M4, appended after the settings. A format-2
/// blob has neither, so generating from one would mean reading them from a
/// live pack — exactly what SPEC §6 forbids — and it is refused instead.
inline constexpr std::uint32_t kBlobFormat = 3;

/// Serialises @p pipeline. Deterministic: the same pipeline gives the same
/// bytes, here and on any other platform.
[[nodiscard]] std::vector<std::byte> write(const Pipeline& pipeline);

/// Reads the header alone, which is what a caller wants when deciding
/// whether a world can be opened at all. Throws FreezeError if the bytes are
/// not a blob this build recognises.
[[nodiscard]] Provenance inspect(std::span<const std::byte> blob);

/// Reads a whole blob. Refuses, naming what is wrong, if the container
/// format or the pipeline engine version is not one this build reproduces,
/// if the content hash does not match, or if the payload is malformed.
///
/// The engine version check is the load-bearing one (SPEC §6): a build that
/// generates differently from the one that wrote the blob must not open the
/// world at all, because the alternative is a seam.
[[nodiscard]] Pipeline read(std::span<const std::byte> blob);

} // namespace stratum::freeze
