// Stratum — Java block state -> Bedrock blockstate.
// Copyright 2026 the Stratum contributors. SPDX-License-Identifier: Apache-2.0
//
// SPEC section 9's platform-neutral half of block state mapping: a Java
// block state this build generated, translated to the named Bedrock
// blockstate `{name, states, version}` both PocketMine-MP
// (`BlockStateData`) and Nukkit (`BlockStateMapping`) already take as input.
// Never a numeric network runtime id — that is protocol-specific and each
// platform derives it downstream. Deliberately downstream of the conformance
// boundary: generation never calls into this library.
//
// The table is generated by tools/mapping-sync from GeyserMC/mappings and a
// GeyserMC/Geyser Bedrock block palette (both MIT) at pinned commits, keyed
// by the pinned Minecraft version's own block state registry.
//
// Resolving is not a per-block operation: a binding resolves each distinct
// state once (a chunk palette, a startup lookup table) and indexes the
// result. `javaBlockStateId` exists for exactly that — a dense id in
// [0, javaBlockStateCount()) a binding can size an array by.
#pragma once

#include <stratum/settings/noise_settings.hpp>

#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string_view>
#include <vector>

namespace stratum::mapping {

/// A block state this build's table cannot place: a block the pinned
/// Minecraft version does not have, a property that block does not have, or
/// a value that property cannot take. Named in the message (SPEC §8).
class BlockMappingError : public std::runtime_error {
public:
    using std::runtime_error::runtime_error;
};

/// The NBT tag a Bedrock blockstate value is stored under. Typed on purpose:
/// to the platforms consuming it, byte 0 and int 0 are different states.
/// Values are the NBT tag ids themselves.
enum class BedrockTagType : std::uint8_t {
    Byte = 1,
    Int = 3,
    String = 8,
};

/// One entry of a Bedrock blockstate's `states` compound.
struct BedrockStateValue {
    std::string_view name;
    BedrockTagType type = BedrockTagType::String;
    /// Set for `Byte` and `Int`.
    std::int32_t integer = 0;
    /// Set for `String`.
    std::string_view string;

    [[nodiscard]] bool operator==(const BedrockStateValue& other) const = default;
};

/// A Bedrock blockstate: `name` is namespaced ("minecraft:snow_layer"),
/// `states` is sorted by name, and `version` is the blockstate version the
/// table was generated at (the same for every state).
struct BedrockBlockState {
    std::string_view name;
    std::vector<BedrockStateValue> states;
    std::int32_t version = 0;

    [[nodiscard]] bool operator==(const BedrockBlockState& other) const = default;
};

/// Vanilla's own id for @p state at the pinned Minecraft version. Properties
/// @p state leaves out take the block's default, the way a data pack's block
/// state does. Throws `BlockMappingError` naming the block and, where it is
/// the problem, the property.
[[nodiscard]] std::uint32_t javaBlockStateId(const settings::BlockState& state);

/// The Bedrock blockstate for Java state id @p javaStateId. Throws
/// `BlockMappingError` if the id is not below `javaBlockStateCount()`.
[[nodiscard]] BedrockBlockState bedrockBlockState(std::uint32_t javaStateId);

/// `bedrockBlockState(javaBlockStateId(state))`.
[[nodiscard]] BedrockBlockState bedrockBlockState(const settings::BlockState& state);

/// How many Java block states the pinned Minecraft version has.
[[nodiscard]] std::size_t javaBlockStateCount() noexcept;

/// The Bedrock blockstate version every state in this table carries —
/// `(major << 24) | (minor << 16) | (patch << 8) | revision`. Not a gate on
/// its own (SPEC §9): a platform on a different version may still accept a
/// given state unchanged, so a binding logs the difference and resolves
/// state by state, sending misses to its fallback table.
[[nodiscard]] std::int32_t bedrockBlockStateVersion() noexcept;

} // namespace stratum::mapping
