<?php

declare(strict_types=1);

namespace Stratum\PMMP;

use pocketmine\block\Block;
use pocketmine\world\ChunkManager;
use pocketmine\world\format\Chunk;
use pocketmine\world\format\PalettedBlockArray;
use pocketmine\world\format\SubChunk;
use pocketmine\world\generator\Generator;

/**
 * Vanilla Java Edition terrain, generated by Stratum's C++ engine.
 *
 * Constructed once per generation worker thread with nothing but the world
 * seed and its options string. Everything expensive happens here, once:
 * opening the world's frozen pipeline compiles it, and the engine shares one
 * compiled dimension across every worker that opens the same blob, settings,
 * list and seed.
 *
 * What generateChunk() does per chunk is deliberately small — the engine
 * returns sub-chunks already packed the way PalettedBlockArray::fromData
 * reads them, so the only PHP work is translating each sub-chunk's handful
 * of palette entries. There is no per-block PHP.
 */
final class StratumGenerator extends Generator{

	private \Stratum\Dimension $dimension;

	private BlockStateTranslator $translator;

	/**
	 * @throws \Stratum\GenerationException if the frozen pipeline cannot be
	 * opened or does not carry this dimension. Thrown on the worker thread
	 * during generator registration, which PocketMine-MP surfaces rather
	 * than generating a world of nothing.
	 */
	public function __construct(int $seed, string $preset){
		parent::__construct($seed, $preset);

		$options = GeneratorOptions::parse($preset);
		$this->dimension = \Stratum\Dimension::open(
			$options->blobPath,
			$options->noiseSettings,
			$options->biomeParameterList,
			$seed
		);
		$this->translator = new BlockStateTranslator();
	}

	public function generateChunk(ChunkManager $world, int $chunkX, int $chunkZ) : void{
		$subChunks = [];
		foreach($this->dimension->encodeChunk($chunkX, $chunkZ) as $subChunkY => $layers){
			$blockLayers = [];
			if($layers["blocks"] !== null){
				[$bitsPerBlock, $wordArray, $javaPalette] = $layers["blocks"];
				$palette = [];
				foreach($javaPalette as $javaStateId){
					// A few entries per sub-chunk, cached across the whole
					// world after the first chunk.
					$palette[] = $this->translator->translate($javaStateId);
				}
				$blockLayers[] = PalettedBlockArray::fromData($bitsPerBlock, $wordArray, $palette);
			}
			// An all-air sub-chunk keeps an empty layer list, which is how
			// PocketMine-MP's own generators represent one.

			// Biomes are Bedrock's own numeric ids, which is what
			// PocketMine-MP stores; no translation step.
			[$biomeBits, $biomeWords, $biomePalette] = $layers["biomes"];

			// Keys are signed sub-chunk indices (-4..19) and Chunk's
			// constructor indexes by exactly that. A 0-based array would
			// build a world shifted vertically, with nothing to say so.
			$subChunks[$subChunkY] = new SubChunk(
				Block::EMPTY_STATE_ID,
				$blockLayers,
				PalettedBlockArray::fromData($biomeBits, $biomeWords, $biomePalette)
			);
		}

		// Every sub-chunk the dimension covers is present: a key Chunk's
		// constructor does not find becomes air AND an all-ocean biome
		// array, which would be a visibly wrong world with no error.
		$world->setChunk($chunkX, $chunkZ, new Chunk($subChunks, terrainPopulated: false));
	}

	public function populateChunk(ChunkManager $world, int $chunkX, int $chunkZ) : void{
		// Nothing: features, structures and decoration are M6 (SPEC section
		// 10) and out of scope for v1. Terrain, surface and aquifers are
		// already in what generateChunk placed.
		//
		// PocketMine-MP marks the chunk populated itself, in
		// PopulationUtils::populateChunkWithAdjacents.
	}
}
