#!/usr/bin/env bash
# Stratum — vanilla's amplified and large_biomes presets, generated by the
# server, with the overworld beside them as a control.
# Copyright 2026 the Stratum contributors. SPDX-License-Identifier: Apache-2.0
#
#   tools/analysis/aquifer-presets-probe.sh --accept-eula [seed]
#       [--amplified-origin <chunkX> <chunkZ>] [--large-biomes-origin <chunkX> <chunkZ>]
#
# WHY THIS EXISTS. `minecraft:amplified` and `minecraft:large_biomes` are pure
# data to Stratum — the same ChunkFiller runs them — but they reach aquifer
# regimes the overworld's goldens barely do: aquifer fluid and barrier above
# sea level under a preliminary surface above 141 (the highest the level rule
# was fitted on), a y_skip cutoff computed from a very high surface, and
# Q5.9's deep-dark override fed by large_biomes' own erosion and depth. Three
# dimensions in one server start:
#
#   amplified     settings minecraft:amplified
#   large_biomes  settings minecraft:large_biomes
#   overworld     settings minecraft:overworld — the CONTROL, at amplified's
#                 window: the two share continents, erosion and ridges, so a
#                 disagreement on amplified that the control does not show
#                 belongs to the preset, not to this harness.
#
# Each takes its settings BY REFERENCE ("settings": "minecraft:<preset>"):
# aquifers, ore veins and all fifteen router entries exactly as shipped,
# nothing copied or overridden. The one substitution is the biome — fixed to
# `stratum:probe`, which has no carvers and no features, as in
# aquifer-on-probe.sh — so a cave or a lake is never what a mismatch is blamed
# on. The aquifer reads no biome.
#
# THE WINDOWS are 8x8 chunks inside r.0.0 (the region the conformance harness
# addresses), at origins chosen offline by `stratum_aquifer_presets_scout`
# from Stratum alone: a blind window shows neither regime. The defaults are
# seed 322's — amplified under a psl above 141, large_biomes where Q5.9
# decides most — and tools/analysis/aquifer-probes.sh also runs seed 163,
# whose amplified window holds aquifer fluid above the sea. The manifest
# records the windows used, and tests/conformance/vanilla_aquifer_presets_test.cpp
# checks them.
#
# Frozen before any chunk generates (density-probe.sh, SPEC §7), and the
# manifest says so. STRATUM_PROBE_OVERWRITE=1 lets a run replace a seed's
# corpus generated at other windows; STRATUM_PROBE_XMX sets the server's heap
# (default 6G).
#
# Read by tests/conformance/vanilla_aquifer_presets_test.cpp. Nothing it writes
# is committed: worlds are Mojang-derived (SPEC §12).
set -euo pipefail

readonly MINECRAFT_VERSION="1.21.11"
readonly CHUNKS=8

accept_eula=0
seed=""
# The windows aquifer-presets-scout chose for the default seed, 322.
amplified_origin=(1 7)
large_origin=(0 19)
while [[ $# -gt 0 ]]; do
    case "$1" in
        --accept-eula) accept_eula=1; shift ;;
        --amplified-origin)
            amplified_origin=("${2:?--amplified-origin needs chunkX chunkZ}"
                              "${3:?--amplified-origin needs chunkX chunkZ}"); shift 3 ;;
        --large-biomes-origin)
            large_origin=("${2:?--large-biomes-origin needs chunkX chunkZ}"
                          "${3:?--large-biomes-origin needs chunkX chunkZ}"); shift 3 ;;
        -*) echo "unknown argument: $1" >&2; exit 2 ;;
        *) [[ -z "${seed}" ]] || { echo "one seed only: $1" >&2; exit 2; }
           seed="$1"; shift ;;
    esac
done
seed="${seed:-322}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"
log() { printf '==> %s\n' "$*" >&2; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

[[ ${accept_eula} -eq 1 ]] || die "this runs the Minecraft server, so it needs --accept-eula"
command -v java >/dev/null 2>&1 || die "java is needed"
command -v python3 >/dev/null 2>&1 || die "python3 is needed"
[[ "${seed}" =~ ^-?[0-9]+$ ]] || die "the seed must be a whole number: ${seed}"
for value in "${amplified_origin[@]}" "${large_origin[@]}"; do
    # Inside r.0.0, all of it: the harness reads chunks 0..31 only.
    [[ "${value}" =~ ^[0-9]+$ ]] && (( value + CHUNKS <= 32 )) \
        || die "a window origin must keep the ${CHUNKS}x${CHUNKS} window inside r.0.0: ${value}"
done
for preset in overworld amplified large_biomes; do
    [[ -f ".fixtures/${MINECRAFT_VERSION}/worldgen/noise_settings/${preset}.json" ]] \
        || die "no ${preset} noise settings; run tools/fetch-vanilla first"
done
jar="$(find ".fixtures/${MINECRAFT_VERSION}" -maxdepth 2 -name 'server*.jar' | head -1)"
[[ -n "${jar}" ]] || die "no server jar; run tools/fetch-vanilla first"
jar="$(cd "$(dirname "${jar}")" && pwd)/$(basename "${jar}")"

out="${repo_root}/.fixtures/${MINECRAFT_VERSION}/probes/aquifer-presets/seed-${seed}"
# The corpus is named after the seed alone, so a run at other windows would
# replace the one the conformance case reads, and the case would then fail as
# if the code had regressed. Regenerating the same windows is the normal case.
if [[ -f "${out}/manifest.json" && -z "${STRATUM_PROBE_OVERWRITE:-}" ]]; then
    existing="$(python3 -c '
import json, sys
dimensions = json.load(open(sys.argv[1])).get("dimensions", {})
print(" ".join(str(c) for name in ("amplified", "large_biomes")
               for c in dimensions.get(name, {}).get("origin_chunk", [])))' "${out}/manifest.json")"
    requested="${amplified_origin[*]} ${large_origin[*]}"
    [[ "${existing}" == "${requested}" ]] \
        || die "${out} holds windows (${existing}), not (${requested}); this run would replace it.
       Set STRATUM_PROBE_OVERWRITE=1 to replace it"
fi

work="$(mktemp -d)"
# The trap takes the server down with the work directory (density-probe.sh).
cleanup() {
    if [[ -n "${server_pid:-}" ]] && kill -0 "${server_pid}" 2>/dev/null; then
        kill "${server_pid}" 2>/dev/null || true
        for _ in 1 2 3 4 5 6 7 8 9 10; do
            kill -0 "${server_pid}" 2>/dev/null || break
            sleep 1
        done
        kill -9 "${server_pid}" 2>/dev/null || true
    fi
    rm -rf "${work}"
}
trap cleanup EXIT INT TERM
server="${work}/server"
pack="${server}/world/datapacks/stratum-aquifer-presets/data/stratum"
mkdir -p "${pack}/dimension" "${pack}/worldgen/biome"

cat > "${server}/world/datapacks/stratum-aquifer-presets/pack.mcmeta" <<'META'
{"pack": {"pack_format": 94, "description": "stratum aquifer presets"}}
META

cat > "${pack}/worldgen/biome/probe.json" <<'BIOME'
{
  "temperature": 0.8, "downfall": 0.4, "has_precipitation": false,
  "effects": {"sky_color": 7907327, "fog_color": 12638463,
              "water_color": 4159204, "water_fog_color": 329011},
  "spawners": {}, "spawn_costs": {}, "carvers": [], "features": []
}
BIOME

names=(amplified large_biomes overworld)
for name in "${names[@]}"; do
    # By reference: the dimension names vanilla's own settings, so nothing in
    # them can drift from what the server ships.
    cat > "${pack}/dimension/${name}.json" <<DIMENSION
{"type": "minecraft:overworld",
 "generator": {"type": "minecraft:noise", "settings": "minecraft:${name}",
               "biome_source": {"type": "minecraft:fixed", "biome": "stratum:probe"}}}
DIMENSION
done

printf 'eula=true\n' > "${server}/eula.txt"
cat > "${server}/server.properties" <<PROPERTIES
level-seed=${seed}
level-name=world
online-mode=false
server-port=0
max-players=1
generate-structures=false
spawn-monsters=false
spawn-npcs=false
spawn-animals=false
sync-chunk-writes=true
max-tick-time=-1
motd=stratum aquifer presets probe
PROPERTIES

pipe="${work}/console"
mkfifo "${pipe}"
log "starting the server (seed ${seed})"
# `exec` so $! is the JVM itself, which is what the trap has to stop.
( cd "${server}" && exec java "-Xmx${STRATUM_PROBE_XMX:-6G}" -jar "${jar}" --nogui \
    < "${pipe}" > "${work}/server.log" 2>&1 ) &
server_pid=$!
exec 3> "${pipe}"

waited=0
while (( waited < 300 )); do
    grep -q 'Done (' "${work}/server.log" 2>/dev/null && break
    kill -0 "${server_pid}" 2>/dev/null || { tail -30 "${work}/server.log" >&2; die "server died at startup"; }
    sleep 5; waited=$((waited + 5))
done
grep -q 'Done (' "${work}/server.log" || { tail -30 "${work}/server.log" >&2; die "server did not start"; }

# Frozen before any chunk generates, as tools/fetch-vanilla freezes the
# goldens (SPEC §7, property 1).
log "freezing the world before generating"
printf 'tick freeze\n' >&3
sleep 2
grep -q -i 'frozen' "${work}/server.log" \
    || { printf 'stop\n' >&3; die "'tick freeze' was not acknowledged"; }

forceload() {
    local name="$1" cx="$2" cz="$3"
    log "forceloading ${CHUNKS}x${CHUNKS} chunks of ${name} from chunk (${cx}, ${cz})"
    printf 'execute in stratum:%s run forceload add %d %d %d %d\n' "${name}" \
        $(( cx * 16 )) $(( cz * 16 )) $(( (cx + CHUNKS) * 16 - 1 )) $(( (cz + CHUNKS) * 16 - 1 )) >&3
}
forceload amplified "${amplified_origin[0]}" "${amplified_origin[1]}"
forceload overworld "${amplified_origin[0]}" "${amplified_origin[1]}"
forceload large_biomes "${large_origin[0]}" "${large_origin[1]}"

waited=0; stable=0; previous=""
while (( waited < 1800 )); do
    kill -0 "${server_pid}" 2>/dev/null || { tail -30 "${work}/server.log" >&2; die "server died"; }
    printf 'save-all flush\n' >&3 || true
    sleep 15; waited=$((waited + 15))
    sizes="$(for name in "${names[@]}"; do
        f="${server}/world/dimensions/stratum/${name}/region/r.0.0.mca"
        [[ -f "${f}" ]] && wc -c < "${f}" || echo -
    done | tr '\n' ' ')"
    present="$(tr ' ' '\n' <<< "${sizes}" | grep -c '^[0-9]' || true)"
    if [[ "${present}" -eq "${#names[@]}" && "${sizes}" == "${previous}" ]]; then
        stable=$((stable + 1)); (( stable >= 2 )) && break
    else
        stable=0
    fi
    previous="${sizes}"
    log "  ${present}/${#names[@]} region(s) present after ${waited}s"
done
(( stable >= 2 )) || { printf 'stop\n' >&3; die "the regions did not settle"; }

printf 'stop\n' >&3
exec 3>&-
wait "${server_pid}" 2>/dev/null || true

mkdir -p "${out}"
for name in "${names[@]}"; do
    mkdir -p "${out}/${name}"
    cp "${server}/world/dimensions/stratum/${name}/region/r.0.0.mca" "${out}/${name}/r.0.0.mca"
done
# What produced the regions, read by the conformance case: the seed, that the
# world was frozen, and each dimension's settings and window.
cat > "${out}/manifest.json" <<MANIFEST
{"seed": ${seed}, "chunks": ${CHUNKS}, "version": "${MINECRAFT_VERSION}", "ticks_frozen": true,
 "dimensions": {
  "amplified": {"settings": "minecraft:amplified",
                "origin_chunk": [${amplified_origin[0]}, ${amplified_origin[1]}]},
  "large_biomes": {"settings": "minecraft:large_biomes",
                   "origin_chunk": [${large_origin[0]}, ${large_origin[1]}]},
  "overworld": {"settings": "minecraft:overworld",
                "origin_chunk": [${amplified_origin[0]}, ${amplified_origin[1]}]}}}
MANIFEST
log "wrote ${out}"
