#!/usr/bin/env bash
# Stratum — measure any density function from the vanilla server itself.
# Copyright 2026 the Stratum contributors. SPDX-License-Identifier: Apache-2.0
#
#   tools/analysis/density-probe.sh --accept-eula --spec <spec.json> [--seed N]
#                                   [--origin-chunk <chunkX> <chunkZ>]
#
# --origin-chunk moves the CHUNKSxCHUNKS block this forceloads away from the
# world origin, and with it the region file collected. It exists because some
# questions are about a specific COLUMN rather than about a function's shape:
# `minecraft:surface`'s own lower tail reaches a negative surface depth on 98
# of 8589934592 columns over the eight golden seeds (1 in 87652393), and the
# columns that do are wherever the noise put them — at seed
# -4172144997902289642 the nearest are at x 2282-2284, z 1879-1880, which is
# chunk (142, 117) and region r.4.3. A probe pinned to r.0.0 cannot see them
# at all. The default is 0 0, i.e. exactly what every existing spec
# already got, and the forceloaded block must lie inside ONE region so the
# collected file is the whole of it.
#
# STRATUM_PROBE_KEEP_WORK=1 in the environment keeps the work directory
# (server, world, generated datapack) instead of deleting it on exit —
# for diagnosing a probe that came back with unexpected output, where the
# question is "what did the server actually see" rather than "what did it
# generate".
#
# THE TRICK. A datapack gives a dimension the entire `final_density`
#
#     K * flat_cache(<the function under test>) + y_clamped_gradient(+1 .. -1)
#
# and nothing else that can place a block. `flat_cache` pins the function to
# y = 0 for the whole column, so the only thing varying with height is the
# gradient, and the surface sits exactly where K*F + g(y) = 0. Invert g and
# every column's terrain height *is* a reading of F(x, 0, z), taken from
# Mojang's own binary. That is how old_blended_noise was confirmed, and it
# generalises to every node with no documentation and no oracle.
#
# WHY A SPEC FILE. One server start costs minutes and one dimension costs
# almost nothing, so a sweep goes in ONE world as many dimensions rather than
# as many worlds. The spec is a JSON array of {"name": ..., "function": ...};
# each entry becomes a dimension, and each dimension's region lands under
# .fixtures/<version>/probes/<spec name>/<entry name>/r.0.0.mca.
#
# Every noise_settings field a probe might want to vary is a PER-ENTRY field
# of that entry, `legacy_random_source` included — a legacy dimension and its
# modern control belong in ONE world, generated by one server start from one
# seed, or the control is not a control. Two sidecars travel with a spec:
# <spec>.biomes.json and <spec>.noises.json, the biomes and the noise
# parameters it names. Both are copied next to the regions, so a recorded
# probe says what produced it.
#
# Two things the first version of this got wrong, both of which read as a
# disagreement rather than as a mistake:
#   * Only CELL CORNERS carry the function's own value. final_density is
#     evaluated on the cell lattice and interpolated across it, and flat_cache
#     pins its argument to the 4x4 column corner as well.
#   * The biome must have NO carvers and NO features. minecraft:plains carves
#     caves through the terrain and puts lakes on top of it.
#
# Nothing this writes is committed: worlds and their regions are Mojang-derived
# (SPEC §12).
set -euo pipefail

readonly MINECRAFT_VERSION="1.21.11"
readonly K="0.35"          # scales the function into the gradient's range
readonly MIN_Y=-64
readonly HEIGHT=384
# Per dimension, squared: 8 -> a 128x128-block FORCELOADED square. What the
# readback then covers is larger, because the server generates a border of
# chunks around the square and the whole region file is copied: at --origin 0
# that is x, z in [0, 191] (the negative half of the border falling in a
# region that is not copied) and at --origin -12 it is x, z in [-256, -1].
# Measured in tests/conformance/vanilla_psl_lattice_test.cpp, "every dimension
# of the sweep, scored twice and with its extent measured".
readonly CHUNKS=8

accept_eula=0
spec=""
seed=42
origin_chunk_x=0
origin_chunk_z=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --accept-eula) accept_eula=1; shift ;;
        --spec)        spec="${2:?--spec needs a file}"; shift 2 ;;
        --seed)        seed="${2:?--seed needs a number}"; shift 2 ;;
        --origin-chunk) origin_chunk_x="${2:?--origin-chunk needs chunkX chunkZ}"
                        origin_chunk_z="${3:?--origin-chunk needs chunkX chunkZ}"; shift 3 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"
log() { printf '==> %s\n' "$*" >&2; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

[[ ${accept_eula} -eq 1 ]] || die "this runs the Minecraft server, so it needs --accept-eula"
[[ -n "${spec}" && -f "${spec}" ]] || die "--spec must name a readable JSON file"
[[ "${origin_chunk_x}" =~ ^-?[0-9]+$ && "${origin_chunk_z}" =~ ^-?[0-9]+$ ]] \
    || die "--origin-chunk takes two whole numbers: chunkX chunkZ"
# Not required to sit on a region boundary — only required not to STRADDLE
# one, which is a weaker condition and is checked exactly, below, once CHUNKS
# is known. An origin a multiple of 32 always satisfies it; so does any origin
# whose window happens to fit.
command -v java >/dev/null 2>&1 || die "java is needed"
command -v python3 >/dev/null 2>&1 || die "python3 is needed"

spec_name="$(basename "${spec}" .json)"
jar="$(find "${repo_root}/.fixtures/${MINECRAFT_VERSION}" -maxdepth 2 -name 'server*.jar' | head -1)"
[[ -n "${jar}" ]] || die "no server jar under .fixtures/${MINECRAFT_VERSION}; run tools/fetch-vanilla first"
jar="$(cd "$(dirname "${jar}")" && pwd)/$(basename "${jar}")"

work="$(mktemp -d)"
# How much heap the server gets. Overridable because several probes may be in
# flight at once — a fan-out of agents each running one — and the default is
# sized for a machine that is otherwise idle. Three concurrent servers at the
# default is most of a 29 GB box; generating 64 chunks needs far less.
probe_xmx="${STRATUM_PROBE_XMX:-6G}"

# The server outlives this script unless it is told not to. An interrupted
# run — Ctrl-C, a killed parent, a session ending — used to leave a JVM
# holding its heap until the machine was rebooted, and three of them at once
# is most of a 29 GB box. So the trap takes the server down as well as the
# work directory, and covers the signals that actually happen rather than only
# a clean exit.
cleanup() {
    if [[ -n "${server_pid:-}" ]] && kill -0 "${server_pid}" 2>/dev/null; then
        kill "${server_pid}" 2>/dev/null || true
        for _ in 1 2 3 4 5 6 7 8 9 10; do
            kill -0 "${server_pid}" 2>/dev/null || break
            sleep 1
        done
        kill -9 "${server_pid}" 2>/dev/null || true
    fi
    if [[ -n "${STRATUM_PROBE_KEEP_WORK:-}" ]]; then
        echo "keeping work dir at ${work} (STRATUM_PROBE_KEEP_WORK set)" >&2
    else
        rm -rf "${work}"
    fi
}
trap cleanup EXIT INT TERM
server="${work}/server"
pack="${server}/world/datapacks/stratum-probe/data/stratum"
mkdir -p "${pack}/dimension" "${pack}/worldgen/noise_settings" "${pack}/worldgen/biome" \
         "${pack}/worldgen/noise"

cat > "${server}/world/datapacks/stratum-probe/pack.mcmeta" <<'META'
{"pack": {"pack_format": 94, "description": "stratum density probe"}}
META

# No carvers, no features. Without this the probe reads the wrong thing.
# A spec may ship extra biomes beside it, as <spec>.biomes.json. `temperature`
# is a condition ON the biome, so probing it means varying one.
biomes_file="${spec%.json}.biomes.json"
if [[ -f "${biomes_file}" ]]; then
    log "writing extra biomes from ${biomes_file}"
    env BIOMES="${biomes_file}" PACK="${pack}" python3 -c '
import json, os, pathlib
pack = pathlib.Path(os.environ["PACK"])
for name, body in json.load(open(os.environ["BIOMES"])).items():
    (pack / "worldgen" / "biome" / (name + ".json")).write_text(json.dumps(body))
'
fi

# The noises a spec names, as <spec>.noises.json: {"stratum:na": {...}, ...}.
# A spec that references a noise it does not ship is a spec nobody can re-run,
# and four of this project's legacy probes were exactly that until the sidecar
# existed. `probe_noise` below is always present; anything else comes from here.
noises_file="${spec%.json}.noises.json"
if [[ -f "${noises_file}" ]]; then
    log "writing extra noises from ${noises_file}"
    env NOISES="${noises_file}" PACK="${pack}" python3 -c '
import json, os, pathlib
pack = pathlib.Path(os.environ["PACK"])
for ident, body in json.load(open(os.environ["NOISES"])).items():
    namespace, _, path = ident.rpartition(":")
    if namespace not in ("", "stratum"):
        raise SystemExit(f"a probe may only define noises under stratum: {ident}")
    (pack / "worldgen" / "noise" / (path + ".json")).write_text(json.dumps(body))
'
fi

cat > "${pack}/worldgen/biome/probe.json" <<'BIOME'
{
  "temperature": 0.8, "downfall": 0.4, "has_precipitation": false,
  "effects": {"sky_color": 7907327, "fog_color": 12638463,
              "water_color": 4159204, "water_fog_color": 329011},
  "spawners": {}, "spawn_costs": {}, "carvers": [], "features": []
}
BIOME

# A noise a probe can name when it needs one it can also compute here. One
# octave, so nothing about it is in doubt.
cat > "${pack}/worldgen/noise/probe_noise.json" <<'NOISE'
{"firstOctave": -3, "amplitudes": [1.0]}
NOISE

log "writing dimensions from ${spec}"
count="$(env SPEC="${spec}" PACK="${pack}" PROBE_K="${K}" PROBE_MIN_Y="${MIN_Y}" \
    PROBE_HEIGHT="${HEIGHT}" python3 - <<'PY'
import json, os, pathlib
spec = json.load(open(os.environ['SPEC']))
pack = pathlib.Path(os.environ['PACK'])
k = float(os.environ['PROBE_K'])
default_min_y = int(os.environ['PROBE_MIN_Y'])
default_height = int(os.environ['PROBE_HEIGHT'])
names = set()
for entry in spec:
    name = entry['name']
    if name in names:
        raise SystemExit(f'duplicate probe name: {name}')
    names.add(name)
    # The world's own vertical extent is per-entry, because where a lattice is
    # ANCHORED can only be told apart from its spacing by moving the floor.
    min_y = int(entry.get('min_y', default_min_y))
    height = int(entry.get('height', default_height))
    # Two shapes. A DENSITY probe wraps the function under test in
    # `K * flat_cache(f) + gradient` so its value shows up as a terrain
    # height. A SURFACE RULE probe does not: it takes `raw_final_density`
    # verbatim — usually a constant, so the column is solid throughout —
    # and a `surface_rule` of its own, and the answer is read from the
    # block identities rather than from a height. Same machinery,
    # different readout.
    if 'raw_final_density' in entry:
        final_density = entry['raw_final_density']
    else:
        final_density = {
            'type': 'minecraft:add',
            'argument1': {'type': 'minecraft:mul', 'argument1': k,
                          'argument2': {'type': 'minecraft:flat_cache',
                                        'argument': entry['function']}},
            'argument2': {'type': 'minecraft:y_clamped_gradient',
                          'from_y': min_y, 'to_y': min_y + height,
                          'from_value': 1.0, 'to_value': -1.0},
        }
    surface_rule = entry.get('surface_rule',
                             {'type': 'minecraft:block',
                              'result_state': {'Name': 'minecraft:stone'}})
    biome = entry.get('biome', 'stratum:probe')
    # The cell shape is per-entry too: a probe that wants to know whether an
    # effect follows the cell lattice has to be able to move the lattice.
    size_vertical = entry.get('size_vertical', 1)
    size_horizontal = entry.get('size_horizontal', 1)
    # Aquifers, and the two settings that only mean anything with them on.
    # A probe that wants to SEE the aquifer has to be able to turn it on and
    # give it a fluid and a sea level to work against; everything else here
    # wants it off, which stays the default. Ore veins are the same kind of
    # flag, with no settings of their own to go with it.
    aquifers = entry.get('aquifers_enabled', False)
    # Ore veins, the same way: off unless a probe asks for it by name.
    ore_veins = entry.get('ore_veins_enabled', False)
    # Which random source the dimension declares — PER ENTRY, because the
    # whole point of a legacy probe is a legacy dimension and its modern
    # control sitting in the SAME world, generated by the same server start
    # from the same seed. A run whose control is in another world is not a
    # control. This was hardcoded False once, which made every legacy
    # measurement this project has taken impossible to reproduce from the
    # repository; see SPEC §11.
    legacy_random_source = bool(entry.get('legacy_random_source', False))
    sea_level = entry.get('sea_level', min_y)
    default_fluid = entry.get('default_fluid', {'Name': 'minecraft:air'})
    # Router entries default to the constant 0 that a density probe wants.
    # `router` overrides them by name, which is how the aquifer's own four
    # inputs get vanilla's noises instead of zero.
    router = {'barrier': 0, 'fluid_level_floodedness': 0, 'fluid_level_spread': 0,
              'lava': 0, 'temperature': 0, 'vegetation': 0, 'continents': 0,
              'erosion': 0, 'depth': 0, 'ridges': 0, 'preliminary_surface_level': 0,
              'vein_toggle': 0, 'vein_ridged': 0, 'vein_gap': 0}
    router.update(entry.get('router', {}))
    router['final_density'] = final_density

    # The DIMENSION TYPE fixes the world's logical height, not the noise
    # settings, so a probe that varies min_y has to ship its own type or the
    # server quietly keeps -64..319 and the sweep measures nothing. That
    # mistake produced a null experiment once already.
    dimension_type = 'minecraft:overworld'
    if min_y != -64 or height != 384:
        dimension_type = f'stratum:{name}'
        (pack / 'dimension_type').mkdir(parents=True, exist_ok=True)
        (pack / 'dimension_type' / f'{name}.json').write_text(json.dumps({
            'ultrawarm': False, 'natural': True, 'coordinate_scale': 1.0,
            'has_skylight': True, 'has_ceiling': False, 'ambient_light': 0.0,
            'monster_spawn_light_level': 0, 'monster_spawn_block_light_limit': 0,
            'piglin_safe': False, 'bed_works': True, 'respawn_anchor_works': False,
            'has_raids': True, 'logical_height': height, 'min_y': min_y, 'height': height,
            'infiniburn': '#minecraft:infiniburn_overworld',
            'effects': 'minecraft:overworld',
        }))

    (pack / 'dimension' / f'{name}.json').write_text(json.dumps({
        'type': dimension_type,
        'generator': {
            'type': 'minecraft:noise',
            'settings': f'stratum:{name}',
            'biome_source': {'type': 'minecraft:fixed', 'biome': biome},
        },
    }))
    (pack / 'worldgen' / 'noise_settings' / f'{name}.json').write_text(json.dumps({
        'sea_level': sea_level,
        'disable_mob_generation': True,
        'aquifers_enabled': aquifers,
        'ore_veins_enabled': ore_veins,
        'legacy_random_source': legacy_random_source,
        'default_block': {'Name': 'minecraft:stone'},
        'default_fluid': default_fluid,
        'noise': {'min_y': min_y, 'height': height,
                  'size_horizontal': size_horizontal,
                  'size_vertical': size_vertical},
        'spawn_target': [],
        'surface_rule': surface_rule,
        'noise_router': router,
    }))
print(len(spec))
PY
)"
log "${count} dimension(s)"

printf 'eula=true\n' > "${server}/eula.txt"
cat > "${server}/server.properties" <<PROPERTIES
level-seed=${seed}
level-name=world
online-mode=false
server-port=0
max-players=1
view-distance=10
simulation-distance=10
generate-structures=false
spawn-monsters=false
spawn-npcs=false
spawn-animals=false
sync-chunk-writes=true
max-tick-time=-1
motd=stratum density probe
PROPERTIES

pipe="${work}/console"
mkfifo "${pipe}"
log "starting the server (seed ${seed})"
# `exec` so the subshell BECOMES java. Without it $! is the subshell, the
# trap kills that, and the JVM it was meant to stop is orphaned — which is
# exactly how three of them survived for thirteen hours.
( cd "${server}" && exec java "-Xmx${probe_xmx}" -jar "${jar}" --nogui < "${pipe}" > "${work}/server.log" 2>&1 ) &
server_pid=$!
exec 3> "${pipe}"

waited=0
while (( waited < 180 )); do
    grep -q 'Done (' "${work}/server.log" 2>/dev/null && break
    kill -0 "${server_pid}" 2>/dev/null || { tail -30 "${work}/server.log" >&2; die "server died at startup"; }
    sleep 5; waited=$((waited + 5))
done
grep -q 'Done (' "${work}/server.log" || { tail -30 "${work}/server.log" >&2; die "server did not start"; }

mapfile -t names < <(python3 -c "
import json,sys
for e in json.load(open('${spec}')): print(e['name'])
")

# Which region file the forceloaded block lands in. Bash's / truncates toward
# zero, so a negative chunk coordinate needs the floor form spelled out —
# the same trap javamath::floorDiv exists for on the C++ side.
floor_div_32() {
    local value="$1"
    if (( value >= 0 )); then
        echo $(( value / 32 ))
    else
        echo $(( -(((-value) + 31) / 32) ))
    fi
}
region_x="$(floor_div_32 "${origin_chunk_x}")"
region_z="$(floor_div_32 "${origin_chunk_z}")"
last_region_x="$(floor_div_32 $(( origin_chunk_x + CHUNKS - 1 )))"
last_region_z="$(floor_div_32 $(( origin_chunk_z + CHUNKS - 1 )))"
if [[ "${region_x}" != "${last_region_x}" || "${region_z}" != "${last_region_z}" ]]; then
    die "the ${CHUNKS}x${CHUNKS} block from chunk (${origin_chunk_x}, ${origin_chunk_z}) straddles
       regions r.${region_x}.${region_z} and r.${last_region_x}.${last_region_z}; move
       --origin-chunk so it lies inside one"
fi
region_file="r.${region_x}.${region_z}.mca"

log "forceloading ${CHUNKS}x${CHUNKS} chunks from chunk (${origin_chunk_x}, ${origin_chunk_z})" \
    "into ${region_file} in each of ${#names[@]} dimension(s)"
from_block_x=$(( origin_chunk_x * 16 ))
from_block_z=$(( origin_chunk_z * 16 ))
to_block_x=$(( (origin_chunk_x + CHUNKS - 1) * 16 + 15 ))
to_block_z=$(( (origin_chunk_z + CHUNKS - 1) * 16 + 15 ))
for name in "${names[@]}"; do
    printf 'execute in stratum:%s run forceload add %d %d %d %d\n' "${name}" \
        "${from_block_x}" "${from_block_z}" "${to_block_x}" "${to_block_z}" >&3
done

expected="${#names[@]}"
waited=0; stable=0; previous=""
while (( waited < 3600 )); do
    kill -0 "${server_pid}" 2>/dev/null || { tail -30 "${work}/server.log" >&2; die "server died during generation"; }
    printf 'save-all flush\n' >&3 || true
    sleep 15; waited=$((waited + 15))
    sizes="$(for name in "${names[@]}"; do
        f="${server}/world/dimensions/stratum/${name}/region/${region_file}"
        [[ -f "${f}" ]] && wc -c < "${f}" || echo -
    done | tr '\n' ' ')"
    present="$(tr ' ' '\n' <<< "${sizes}" | grep -c '^[0-9]' || true)"
    if [[ "${present}" -eq "${expected}" && "${sizes}" == "${previous}" ]]; then
        stable=$((stable + 1)); (( stable >= 2 )) && break
    else
        stable=0
    fi
    previous="${sizes}"
    log "  ${present}/${expected} region(s) present after ${waited}s"
done
(( stable >= 2 )) || { printf 'stop\n' >&3; die "regions did not settle within 3600s"; }

printf 'stop\n' >&3
exec 3>&-
wait "${server_pid}" 2>/dev/null || true

out_root="${repo_root}/.fixtures/${MINECRAFT_VERSION}/probes/${spec_name}"
mkdir -p "${out_root}"
for name in "${names[@]}"; do
    mkdir -p "${out_root}/${name}"
    cp "${server}/world/dimensions/stratum/${name}/region/${region_file}" \
       "${out_root}/${name}/${region_file}"
done
cat > "${out_root}/manifest.json" <<MANIFEST
{"seed": ${seed}, "k": ${K}, "min_y": ${MIN_Y}, "height": ${HEIGHT},
 "chunks": ${CHUNKS}, "version": "${MINECRAFT_VERSION}",
 "origin_chunk": [${origin_chunk_x}, ${origin_chunk_z}], "region": "${region_file}",
 "probe_noise": {"id": "stratum:probe_noise", "first_octave": -3, "amplitudes": [1.0]}}
MANIFEST
cp "${spec}" "${out_root}/spec.json"
# The sidecars travel with the regions. A fixture that records the dimensions
# but not the noises they sample cannot be re-scored, let alone regenerated.
if [[ -f "${biomes_file}" ]]; then cp "${biomes_file}" "${out_root}/spec.biomes.json"; fi
if [[ -f "${noises_file}" ]]; then cp "${noises_file}" "${out_root}/spec.noises.json"; fi
log "wrote ${expected} region(s) under ${out_root}"
