// Stratum — reading the legacy-seeded climate noises out of the Nether's own
// stored biomes.
// Copyright 2026 the Stratum contributors. SPDX-License-Identifier: Apache-2.0
//
// WHAT THIS IS FOR. How a NAMED noise's identifier becomes a Java LCG seed
// under `legacy_random_source` is unsolved (SPEC §11). tools/analysis/
// legacy-seed-analyze.cpp attacks it through synthetic probe dimensions whose
// terrain height is a readback of one noise; this file attacks it through a
// different oracle entirely — the eight golden Nether regions, which are the
// real server's own output from the real legacy seeding of the real noises.
//
// THE ORACLE. `.fixtures/1.21.11/regions/seed-<s>/nether/r.0.0.mca` at seeds
// 0, 1, -1, 42, 2891948927356891, -4172144997902289642, Long.MAX_VALUE and
// Long.MIN_VALUE. Those eight are SIX INDEPENDENT WORLDS, not eight: a legacy
// dimension's randomness is `new java.util.Random(worldSeed)`, whose scramble
// keeps only the low 48 bits of the seed, so 0 collides with Long.MIN_VALUE
// and -1 with Long.MAX_VALUE. Say six worlds. The scan below uses the six
// distinct ones; only the modern-rule sanity check uses all eight, because
// the number it has to reproduce was measured over all eight.
//
// THE READBACK. The Nether's `biome_source` is multi_noise, and its router
// sets continents, erosion, depth and ridges to the constant 0.0 — so of the
// six climate parameters only `temperature` and `vegetation` vary, and the
// biome stored at a 4x4x4 cell is a function of those two alone. Three noises
// feed them:
//
//     shift_x = flat_cache(cache_2d(shift_a(minecraft:offset)))
//     shift_z = flat_cache(cache_2d(shift_b(minecraft:offset)))
//     temperature = shifted_noise(minecraft:temperature,
//                                 shift_x, 0.0, shift_z, xz_scale 0.25,
//                                 y_scale 0.0)
//     vegetation  = the same over minecraft:vegetation
//
// so each stored biome is a COARSE readback of (temperature, vegetation,
// offset) at that column: not a number, a cell of a five-way partition of the
// (T, H) plane. That is far less information per column than the terrain-height
// readback legacy-seed-analyze inverts — but there are ~2 million columns of
// it, it comes from vanilla's own noises rather than from a synthetic probe,
// and it needs no probe world at all.
//
// THE PARAMETER TABLE, and where it comes from. The pack ships
// `worldgen/multi_noise_biome_source_parameter_list/nether.json` as nothing
// but `{"preset": "minecraft:nether"}`; the five parameter points are compiled
// into the jar. This project does NOT read them off minecraft.wiki and does
// NOT read the jar's code: `tools/fetch-vanilla` runs the server's own data
// generator (`--reports`) and keeps what it dumps at
// `.fixtures/<version>/biome_parameters/minecraft/nether.json`. That is
// observed output of the vanilla server, which CLAUDE.md permits where it
// forbids the source. `--preset` below prints the table it loaded, so the
// numbers a run depends on are visible in the run rather than quoted from
// memory. See lib/include/stratum/biome/parameter_list.hpp.
//
// THE CONTROL COMES FIRST, and it is three separate things, because a
// readback is worthless until the thing that decodes it has been shown to
// recover a rule whose seeding is already known and correct.
//
//   --control  THE DECODER. The overworld goldens at the same eight seeds are
//              generated by the MODERN seeding, which this build reproduces
//              exactly. Run the identical decode — stored biome per cell
//              against `biome::ParameterList::find` over the dimension's own
//              climate router — and the modern rule must come back at ~100%,
//              while the same rule at worldSeed + 1 must fall to the null.
//              The positive arm says the decoder can see a correct seeding;
//              the negative arm says it is the SEEDING doing the work and not
//              the decoder accepting anything. Neither arm alone is a control.
//
//   --model    THE FORWARD MODEL. The scan cannot use the library's
//              `NormalNoise`, which only builds from Xoroshiro128++; it needs
//              a hand-rolled stack over Perlin blocks drawn from a candidate
//              generator, and a hand-rolled climate chain over that. Both
//              halves are compared against the library, bit for bit, at the
//              modern seeding where the library is known right:
//
//                stack   this file's sampleNormal over modernBlocksFor
//                        against noise::NormalNoise::sample, for each of the
//                        THREE noises in play — not for some other noise with
//                        a convenient amplitude list
//                chain   this file's shift/shifted_noise/flat_cache chain over
//                        library NormalNoises, against
//                        density::Interpreter evaluating the Nether's own
//                        router entries
//                whole   the composition of the two against the Interpreter
//
//              A wrong valueFactor, a missing second stack, a wrong
//              persistence schedule or a misread of `shift_b`'s axis rotation
//              is caught here rather than shared silently between the scan and
//              its own null.
//
//   --modern   THE NUMBER ALREADY ON RECORD.
//              tests/conformance/vanilla_legacy_nether_climate_gap_test.cpp
//              measured the MODERN derivation at 27.08% biome agreement on the
//              Nether against a 30.23% chance baseline. This file must
//              reproduce both to the cell before anything it says about
//              candidates is worth reading.
//
// ONLY THEN --scan. The candidate space is legacy-seed-analyze.cpp's, read out
// of that file and re-implemented here rather than shared, because that file
// belongs to a different piece of work and nothing in this one may edit it:
//
//   base       (5)  worldSeed; JavaRandom(worldSeed).nextLong(); the low half
//                   of Xoroshiro128PlusPlus(worldSeed).nextLong(); the LCG's
//                   own scramble of the world seed; zero
//   salt      (10)  MD5("ns:path") as first-eight big-endian, first-eight
//                   little-endian, last-eight big-endian, last-eight
//                   little-endian, lo^hi, lo+hi; MD5("path") first-eight
//                   big-endian; String.hashCode("ns:path");
//                   String.hashCode("path"); no salt
//   combine    (3)  base ^ salt, base + salt, base - salt
//   forks      (3)  0, 1 or 2 further rounds of seed = JavaRandom(seed).nextLong()
//   generator  (2)  the Java LCG, or Xoroshiro128++
//   block    (300)  complete Perlin blocks drawn and discarded first
//
// 5 x 10 x 3 x 3 x 2 = 900 seed rules x 300 block offsets = 270,000
// candidates. The rule index is the SAME index legacy-seed-analyze prints, so
// `--candidate 182 0` names deepslate's own derivation in both tools; the
// agreement between the two enumerations is asserted by
// tests/conformance/vanilla_legacy_goldens_biome_test.cpp rather than left to
// the two headers agreeing in prose.
//
// WHAT THE SCAN DOES NOT COVER, stated here and not left to be assumed. It
// inherits every gap of the space it borrows: ONE stack rule (sequential
// Perlin blocks out of one generator), NO frequency variation, NO per-octave
// salting, and no LCG-STEP skip of the kind `minecraft:end_islands` turned out
// to use. And it adds one of its own: the three noises are seeded by ONE rule
// at ONE block offset. A derivation that seeded `offset` differently from
// `temperature`, or that drew all three from a single shared generator in
// declaration order, is outside this space even though every individual noise's
// rule might be inside it. `--split` measures how much that matters by scoring
// temperature and vegetation with `offset` held at its correct-by-assumption
// zero shift; it does not close the gap.
//
// AND THE READBACK'S OWN POWER IS BOUNDED, which is the honest part. A column
// carries at most log2(5) = 2.32 bits and in practice far less, because the
// five cells are wildly unequal in area. Two DIFFERENT climate fields agree on
// a biome about 30% of the time by construction — that is the chance baseline
// `--modern` prints — so the scan cannot distinguish "nearly right" from
// "unrelated", only "exactly right" (100%) from everything else. It is a sieve
// for a correct rule, not a gradient towards one.
//
//   cmake --build --preset release --target stratum_legacy_goldens_biome_analyze
//   A=build/release/tools/analysis/stratum_legacy_goldens_biome_analyze
//   $A .fixtures --preset
//   $A .fixtures --control
//   $A .fixtures --model
//   $A .fixtures --modern
//   $A .fixtures --boundary
//   $A .fixtures --candidate 182 0
//   $A .fixtures --scan            # ~hours in Debug; use the release preset
//
// The fixtures are Mojang-derived and never committed (SPEC §12). Without them
// every mode exits 77, CTest's skip code.
#include <stratum/biome/parameter_list.hpp>
#include <stratum/chunk/chunk.hpp>
#include <stratum/data/pack.hpp>
#include <stratum/data/registry.hpp>
#include <stratum/data/resource_location.hpp>
#include <stratum/density/interpreter.hpp>
#include <stratum/density/noise_parameters.hpp>
#include <stratum/density/noise_registry.hpp>
#include <stratum/hash/md5.hpp>
#include <stratum/nbt/reader.hpp>
#include <stratum/noise/perlin.hpp>
#include <stratum/region/region_file.hpp>
#include <stratum/rng/java_random.hpp>
#include <stratum/rng/xoroshiro128.hpp>
#include <stratum/settings/noise_settings.hpp>

#include <nlohmann/json.hpp>

#include <algorithm>
#include <array>
#include <bit>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

using namespace stratum;

namespace {

// --- the worlds -------------------------------------------------------------

/// The eight seeds the goldens were generated at. Six worlds: a legacy
/// dimension's randomness is the Java LCG, whose scramble keeps only the low 48
/// bits, so 0 == Long.MIN_VALUE and -1 == Long.MAX_VALUE.
constexpr std::array<std::int64_t, 8> kAllSeeds{
    0,
    1,
    -1,
    42,
    2891948927356891LL,
    -4172144997902289642LL,
    9223372036854775807LL,
    -9223372036854775807LL - 1,
};

/// The six distinct worlds, which is what the scan scores over. Quoting a
/// denominator built from all eight would double two of them.
constexpr std::array<std::int64_t, 6> kDistinctSeeds{
    0, 1, -1, 42, 2891948927356891LL, -4172144997902289642LL,
};

/// Matches tests/conformance/vanilla_legacy_nether_climate_gap_test.cpp: every
/// second chunk of the 32x32 region, so the sample spans all 512x512 blocks.
/// Over a smaller span the Nether is essentially one biome and "agreement"
/// stops measuring anything.
constexpr std::int32_t kNetherChunkStride = 2;

/// The nether's climate carries `y_scale: 0.0` and `shift_y: 0.0`, so its
/// biome is constant down a column. Asserted on vanilla's own stored biomes by
/// the conformance case rather than assumed here, and then used: one y per
/// column instead of thirty-two.
constexpr std::int32_t kNetherSampleY = 64;

[[nodiscard]] std::filesystem::path findUnder(const std::filesystem::path& root,
                                              std::string_view filename,
                                              std::string_view grandparent) {
    if (!std::filesystem::is_directory(root)) {
        return {};
    }
    for (const auto& entry : std::filesystem::recursive_directory_iterator(root)) {
        if (entry.is_regular_file() && entry.path().filename() == filename &&
            entry.path().parent_path().parent_path().filename() == grandparent) {
            return entry.path();
        }
    }
    return {};
}

[[nodiscard]] std::filesystem::path findWorldgenTree(const std::filesystem::path& root) {
    if (!std::filesystem::is_directory(root)) {
        return {};
    }
    for (const auto& entry : std::filesystem::recursive_directory_iterator(root)) {
        if (entry.is_directory() && entry.path().filename() == "worldgen" &&
            std::filesystem::is_directory(entry.path() / "density_function")) {
            return entry.path();
        }
    }
    return {};
}

[[nodiscard]] std::filesystem::path regionOf(const std::filesystem::path& root, std::int64_t seed,
                                             std::string_view dimension) {
    if (!std::filesystem::is_directory(root)) {
        return {};
    }
    const std::string wanted = "seed-" + std::to_string(seed);
    for (const auto& entry : std::filesystem::recursive_directory_iterator(root)) {
        if (!entry.is_regular_file() || entry.path().filename() != "r.0.0.mca") {
            continue;
        }
        const std::filesystem::path parent = entry.path().parent_path();
        if (parent.filename() == dimension && parent.parent_path().filename() == wanted) {
            return entry.path();
        }
    }
    return {};
}

// --- the readback -----------------------------------------------------------

/// One 4x4x4 cell of a golden region: where it is, and which biome vanilla
/// stored there. `biome` indexes the parameter list's own entry order, so the
/// scoring loop compares two small integers instead of two strings.
struct Cell {
    std::int32_t x = 0;
    std::int32_t y = 0;
    std::int32_t z = 0;
    std::uint16_t biome = 0;
    /// True when at least one of the four cells 4 blocks away inside the same
    /// chunk carries a DIFFERENT stored biome. Those columns sit within one
    /// cell of a partition boundary, where an arbitrarily small error in the
    /// climate field flips the answer, so they are the ones a near-miss
    /// candidate gets wrong for free and a wrong one gets right for free.
    /// Counted so the denominator can be stated with and without them.
    bool boundary = false;
};

struct World {
    std::int64_t seed = 0;
    std::vector<Cell> cells;
    /// Cells whose stored biome is not the same all the way down the column.
    /// Must be zero; the Nether's `y_scale: 0.0` requires it.
    std::size_t varyingWithY = 0;
};

/// Maps a stored biome name onto the parameter list's entry order. A name the
/// table does not contain is an error rather than a bucket: the Nether's five
/// biomes are the whole table, and a sixth would mean the table being read is
/// not the one the world was generated from.
class BiomeIndex {
public:
    explicit BiomeIndex(const biome::ParameterList& table) {
        for (const auto& entry : table.entries()) {
            const std::string name = entry.biome.toString();
            if (!index_.contains(name)) {
                index_.emplace(name, names_.size());
                names_.push_back(name);
            }
        }
    }

    [[nodiscard]] std::optional<std::uint16_t> find(const std::string& name) const {
        const auto found = index_.find(name);
        if (found == index_.end()) {
            return std::nullopt;
        }
        return static_cast<std::uint16_t>(found->second);
    }

    [[nodiscard]] const std::string& nameOf(std::uint16_t at) const { return names_[at]; }

    [[nodiscard]] std::size_t size() const noexcept { return names_.size(); }

private:
    std::map<std::string, std::size_t> index_;
    std::vector<std::string> names_;
};

/// Reads one golden Nether region into cells. @p chunkStride subsamples
/// chunks; the cells inside a chunk are always all sixteen, so the
/// boundary test below always has its neighbours.
[[nodiscard]] World readNetherWorld(const std::filesystem::path& region, std::int64_t seed,
                                    const BiomeIndex& biomes, std::int32_t chunkStride) {
    World world;
    world.seed = seed;
    const region::RegionFile file = region::RegionFile::open(region);
    for (std::int32_t chunkZ = 0; chunkZ < region::kChunksPerAxis; chunkZ += chunkStride) {
        for (std::int32_t chunkX = 0; chunkX < region::kChunksPerAxis; chunkX += chunkStride) {
            if (!file.hasChunk(chunkX, chunkZ)) {
                continue;
            }
            const chunk::Chunk decoded =
                chunk::Chunk::decode(nbt::read(file.readChunk(chunkX, chunkZ)).root);

            std::array<std::optional<std::uint16_t>, 16> local{};
            for (int cellZ = 0; cellZ < 4; ++cellZ) {
                for (int cellX = 0; cellX < 4; ++cellX) {
                    const auto offset =
                        (static_cast<std::size_t>(cellZ) * 4U) + static_cast<std::size_t>(cellX);
                    const std::string* columnBiome = nullptr;
                    const std::string* atSampleY = nullptr;
                    for (const auto& section : decoded.sections()) {
                        if (section.biomes.empty()) {
                            continue;
                        }
                        for (int cellY = 0; cellY < 4; ++cellY) {
                            const std::size_t index =
                                (static_cast<std::size_t>(cellY) * 16U) + offset;
                            if (index >= section.biomes.size()) {
                                continue;
                            }
                            const std::string& here = section.biomePalette[section.biomes[index]];
                            if (columnBiome == nullptr) {
                                columnBiome = &here;
                            } else if (here != *columnBiome) {
                                ++world.varyingWithY;
                            }
                            if ((section.y * 16) + (cellY * 4) == kNetherSampleY) {
                                atSampleY = &here;
                            }
                        }
                    }
                    if (atSampleY == nullptr) {
                        continue;
                    }
                    const std::optional<std::uint16_t> found = biomes.find(*atSampleY);
                    if (!found.has_value()) {
                        std::fprintf(stderr,
                                     "golden nether region stores biome '%s', which the loaded "
                                     "parameter list does not contain\n",
                                     atSampleY->c_str());
                        std::exit(1);
                    }
                    local[offset] = found;
                }
            }

            for (int cellZ = 0; cellZ < 4; ++cellZ) {
                for (int cellX = 0; cellX < 4; ++cellX) {
                    const auto offset =
                        (static_cast<std::size_t>(cellZ) * 4U) + static_cast<std::size_t>(cellX);
                    if (!local[offset].has_value()) {
                        continue;
                    }
                    bool boundary = false;
                    constexpr std::array<std::array<int, 2>, 4> kNeighbours{
                        {{-1, 0}, {1, 0}, {0, -1}, {0, 1}}};
                    for (const auto& step : kNeighbours) {
                        const int nx = cellX + step[0];
                        const int nz = cellZ + step[1];
                        if (nx < 0 || nx > 3 || nz < 0 || nz > 3) {
                            continue;
                        }
                        const auto at =
                            (static_cast<std::size_t>(nz) * 4U) + static_cast<std::size_t>(nx);
                        if (local[at].has_value() && *local[at] != *local[offset]) {
                            boundary = true;
                        }
                    }
                    world.cells.push_back(Cell{.x = (chunkX * 16) + (cellX * 4),
                                               .y = kNetherSampleY,
                                               .z = (chunkZ * 16) + (cellZ * 4),
                                               .biome = *local[offset],
                                               .boundary = boundary});
                }
            }
        }
    }
    return world;
}

// --- the forward model ------------------------------------------------------
//
// A NormalNoise built from Perlin blocks this file draws itself, because
// noise::NormalNoise only builds from Xoroshiro128++ and half the candidate
// space drives a Java LCG. Compared against the library bit for bit by
// --model, for the three noises actually in play.

struct Layout {
    struct Octave {
        std::size_t block = 0;
        double amplitude = 0.0;
        double persistence = 0.0;
        double frequency = 0.0;
    };

    std::vector<Octave> first;
    std::vector<Octave> second;
    double valueFactor = 1.0;
    std::size_t blocksPerNoise = 0;
};

/// `amplitude != 0.0`, spelled so the project's -Wfloat-equal does not fire.
[[nodiscard]] bool nonZero(double amplitude) {
    return std::abs(amplitude) > 0.0;
}

[[nodiscard]] Layout layoutFor(const density::NoiseParameters& parameters) {
    Layout layout;
    const auto count = static_cast<int>(parameters.amplitudes.size());
    std::size_t block = 0;
    for (std::vector<Layout::Octave>* stack : {&layout.first, &layout.second}) {
        double frequency = std::ldexp(1.0, parameters.firstOctave);
        double persistence = std::ldexp(1.0, count - 1) / (std::ldexp(1.0, count) - 1.0);
        for (const double amplitude : parameters.amplitudes) {
            if (nonZero(amplitude)) {
                stack->push_back({block, amplitude, persistence, frequency});
                ++block;
            }
            frequency *= 2.0;
            persistence *= 0.5;
        }
    }
    layout.blocksPerNoise = block;

    std::size_t first = 0;
    std::size_t last = parameters.amplitudes.size();
    while (last > first && !nonZero(parameters.amplitudes[last - 1])) {
        --last;
    }
    while (first < last && !nonZero(parameters.amplitudes[first])) {
        ++first;
    }
    const auto effective = static_cast<double>(last - first);
    layout.valueFactor = (1.0 / 6.0) / (0.1 * (1.0 + (1.0 / effective)));
    return layout;
}

[[nodiscard]] double sampleStack(const std::vector<Layout::Octave>& stack,
                                 const std::vector<noise::PerlinNoise>& blocks, std::size_t offset,
                                 double x, double y, double z) {
    double total = 0.0;
    for (const Layout::Octave& octave : stack) {
        const noise::PerlinNoise& perlin = blocks[offset + octave.block];
        total += (perlin.sample(x * octave.frequency, y * octave.frequency, z * octave.frequency) *
                  octave.amplitude) *
                 octave.persistence;
    }
    return total;
}

[[nodiscard]] double sampleNormal(const Layout& layout,
                                  const std::vector<noise::PerlinNoise>& blocks, std::size_t offset,
                                  double x, double y, double z) {
    constexpr double kSecondFrequency = 337.0 / 331.0;
    const double combined = sampleStack(layout.first, blocks, offset, x, y, z) +
                            sampleStack(layout.second, blocks, offset, x * kSecondFrequency,
                                        y * kSecondFrequency, z * kSecondFrequency);
    return combined * layout.valueFactor;
}

/// The Perlin blocks the MODERN rule draws, in the order layoutFor indexes
/// them. lib/src/noise_registry.cpp's positional fork plus lib/src/perlin.cpp's
/// per-octave "octave_<n>" salt, spelled out rather than reached through
/// OctaveNoise, because the point of the `stack` arm is to drive THIS FILE'S
/// sampleNormal.
[[nodiscard]] std::vector<noise::PerlinNoise>
modernBlocksFor(const density::NoiseParameters& parameters, std::string_view id,
                std::int64_t worldSeed) {
    const rng::XoroshiroPositionalFactory factory{worldSeed};
    rng::Xoroshiro128PlusPlus random = factory.fromHashOf(id);
    std::vector<noise::PerlinNoise> blocks;
    for (int stack = 0; stack < 2; ++stack) {
        const auto baseLo = static_cast<std::uint64_t>(random.nextLong());
        const auto baseHi = static_cast<std::uint64_t>(random.nextLong());
        for (std::size_t i = 0; i < parameters.amplitudes.size(); ++i) {
            if (!nonZero(parameters.amplitudes[i])) {
                continue;
            }
            const std::string name =
                "octave_" + std::to_string(parameters.firstOctave + static_cast<int>(i));
            const rng::Seed128 salt = rng::seedFromHashOf(name);
            rng::Xoroshiro128PlusPlus octaveRandom{
                rng::Seed128{.lo = baseLo ^ salt.lo, .hi = baseHi ^ salt.hi}};
            blocks.push_back(noise::PerlinNoise::fromRandom(octaveRandom));
        }
    }
    return blocks;
}

// --- the climate chain ------------------------------------------------------
//
// The Nether's temperature and vegetation router entries, hand-rolled over a
// pair of sampling functions so that the noises behind them can be the
// library's or a candidate's. Checked against density::Interpreter by --model.

struct Climate {
    double temperature = 0.0;
    double vegetation = 0.0;
};

/// The chain, written out: shift_a and shift_b over `offset` at the flat_cache
/// corner, then each climate noise at 0.25 * position plus its shift.
///
/// `flat_cache` relocates rather than merely remembers — vanilla fills it once
/// per 4x4 column at y = 0 — but every cell this file samples is already at a
/// multiple of 4 in x and z, so the corner IS the sample point and the
/// relocation is the identity here. Stated because it is an assumption, and
/// asserted by --model rather than by this comment.
template<typename OffsetNoise, typename TemperatureNoise, typename VegetationNoise>
[[nodiscard]] Climate climateAt(const OffsetNoise& offset, const TemperatureNoise& temperature,
                                const VegetationNoise& vegetation, double x, double z) {
    const double shiftX = offset(x * 0.25, 0.0, z * 0.25) * 4.0;
    const double shiftZ = offset(z * 0.25, x * 0.25, 0.0) * 4.0;
    return Climate{.temperature = temperature((x * 0.25) + shiftX, 0.0, (z * 0.25) + shiftZ),
                   .vegetation = vegetation((x * 0.25) + shiftX, 0.0, (z * 0.25) + shiftZ)};
}

[[nodiscard]] biome::ClimateSample sampleOf(const Climate& climate) {
    return biome::ClimateSample{.temperature = climate.temperature,
                                .humidity = climate.vegetation,
                                .continentalness = 0.0,
                                .erosion = 0.0,
                                .depth = 0.0,
                                .weirdness = 0.0};
}

// --- the candidate space ----------------------------------------------------
//
// tools/analysis/legacy-seed-analyze.cpp's, re-implemented here so that this
// file owns no line of that one. The rule INDEX must agree between the two;
// the conformance case asserts it rather than trusting these two headers to
// stay in step.

enum class Base : std::uint8_t { WorldSeed, LcgLong, XoroLo, Scrambled, Zero };
enum class Salt : std::uint8_t {
    Md5FirstBe,
    Md5FirstLe,
    Md5LastBe,
    Md5LastLe,
    Md5LoXorHi,
    Md5LoPlusHi,
    Md5PathFirstBe,
    HashCodeId,
    HashCodePath,
    None
};
enum class Combine : std::uint8_t { Xor, Add, Sub };
enum class Generator : std::uint8_t { Lcg, Xoroshiro };

constexpr std::size_t kBases = 5;
constexpr std::size_t kSalts = 10;
constexpr std::size_t kCombines = 3;
constexpr std::size_t kForks = 3;
constexpr std::size_t kGenerators = 2;
constexpr std::size_t kSeedRules = kBases * kSalts * kCombines * kForks * kGenerators;
constexpr std::size_t kBlockOffsets = 300;

struct SeedRule {
    Base base = Base::WorldSeed;
    Salt salt = Salt::None;
    Combine combine = Combine::Xor;
    int forks = 0;
    Generator generator = Generator::Lcg;
};

[[nodiscard]] SeedRule ruleAt(std::size_t index) {
    SeedRule rule;
    rule.generator = static_cast<Generator>(index % kGenerators);
    index /= kGenerators;
    rule.forks = static_cast<int>(index % kForks);
    index /= kForks;
    rule.combine = static_cast<Combine>(index % kCombines);
    index /= kCombines;
    rule.salt = static_cast<Salt>(index % kSalts);
    index /= kSalts;
    rule.base = static_cast<Base>(index % kBases);
    return rule;
}

[[nodiscard]] std::string describe(const SeedRule& rule) {
    static constexpr std::array<const char*, kBases> kBaseNames{"worldSeed", "lcgLong", "xoroLo",
                                                                "scrambled", "zero"};
    static constexpr std::array<const char*, kSalts> kSaltNames{
        "md5FirstBE",  "md5FirstLE",     "md5LastBE",  "md5LastLE",    "md5LoXorHi",
        "md5LoPlusHi", "md5PathFirstBE", "hashCodeId", "hashCodePath", "none"};
    static constexpr std::array<const char*, kCombines> kCombineNames{"xor", "add", "sub"};
    return std::string{kBaseNames[static_cast<std::size_t>(rule.base)]} + " " +
           kCombineNames[static_cast<std::size_t>(rule.combine)] + " " +
           kSaltNames[static_cast<std::size_t>(rule.salt)] + ", forks " +
           std::to_string(rule.forks) + ", " +
           (rule.generator == Generator::Lcg ? "lcg" : "xoroshiro");
}

[[nodiscard]] std::uint64_t beU64(const hash::Md5Digest& digest, std::size_t at) {
    std::uint64_t value = 0;
    for (std::size_t i = 0; i < 8; ++i) {
        value = (value << 8U) | digest[at + i];
    }
    return value;
}

[[nodiscard]] std::uint64_t leU64(const hash::Md5Digest& digest, std::size_t at) {
    std::uint64_t value = 0;
    for (std::size_t i = 0; i < 8; ++i) {
        value |= static_cast<std::uint64_t>(digest[at + i]) << (8U * i);
    }
    return value;
}

[[nodiscard]] std::int32_t javaHashCode(std::string_view text) {
    std::uint32_t hash = 0;
    for (const char character : text) {
        hash = (hash * 31U) + static_cast<std::uint32_t>(static_cast<unsigned char>(character));
    }
    return static_cast<std::int32_t>(hash);
}

[[nodiscard]] std::uint64_t saltFor(Salt salt, std::string_view id) {
    const std::size_t colon = id.find(':');
    const std::string_view path = colon == std::string_view::npos ? id : id.substr(colon + 1);
    const hash::Md5Digest digest = hash::md5(id);
    const hash::Md5Digest pathDigest = hash::md5(path);
    switch (salt) {
        case Salt::Md5FirstBe:
            return beU64(digest, 0);
        case Salt::Md5FirstLe:
            return leU64(digest, 0);
        case Salt::Md5LastBe:
            return beU64(digest, 8);
        case Salt::Md5LastLe:
            return leU64(digest, 8);
        case Salt::Md5LoXorHi:
            return beU64(digest, 0) ^ beU64(digest, 8);
        case Salt::Md5LoPlusHi:
            return beU64(digest, 0) + beU64(digest, 8);
        case Salt::Md5PathFirstBe:
            return beU64(pathDigest, 0);
        case Salt::HashCodeId:
            return static_cast<std::uint64_t>(static_cast<std::int64_t>(javaHashCode(id)));
        case Salt::HashCodePath:
            return static_cast<std::uint64_t>(static_cast<std::int64_t>(javaHashCode(path)));
        case Salt::None:
            return 0;
    }
    return 0;
}

[[nodiscard]] std::uint64_t baseFor(Base base, std::int64_t worldSeed) {
    switch (base) {
        case Base::WorldSeed:
            return static_cast<std::uint64_t>(worldSeed);
        case Base::LcgLong: {
            rng::JavaRandom random{worldSeed};
            return static_cast<std::uint64_t>(random.nextLong());
        }
        case Base::XoroLo: {
            rng::Xoroshiro128PlusPlus random{worldSeed};
            return static_cast<std::uint64_t>(random.nextLong());
        }
        case Base::Scrambled:
            return (static_cast<std::uint64_t>(worldSeed) ^ UINT64_C(0x5DEECE66D)) &
                   ((UINT64_C(1) << 48U) - 1);
        case Base::Zero:
            return 0;
    }
    return 0;
}

[[nodiscard]] std::int64_t seedFor(const SeedRule& rule, std::int64_t worldSeed,
                                   std::string_view id) {
    const std::uint64_t base = baseFor(rule.base, worldSeed);
    const std::uint64_t salt = saltFor(rule.salt, id);
    std::uint64_t seed = 0;
    switch (rule.combine) {
        case Combine::Xor:
            seed = base ^ salt;
            break;
        case Combine::Add:
            seed = base + salt;
            break;
        case Combine::Sub:
            seed = base - salt;
            break;
    }
    for (int i = 0; i < rule.forks; ++i) {
        rng::JavaRandom random{static_cast<std::int64_t>(seed)};
        seed = static_cast<std::uint64_t>(random.nextLong());
    }
    return static_cast<std::int64_t>(seed);
}

[[nodiscard]] std::vector<noise::PerlinNoise> blocksFor(const SeedRule& rule, std::int64_t seed,
                                                        std::size_t needed) {
    std::vector<noise::PerlinNoise> blocks;
    blocks.reserve(needed);
    if (rule.generator == Generator::Lcg) {
        rng::JavaRandom random{seed};
        for (std::size_t i = 0; i < needed; ++i) {
            blocks.push_back(noise::PerlinNoise::fromRandom(random));
        }
    } else {
        rng::Xoroshiro128PlusPlus random{seed};
        for (std::size_t i = 0; i < needed; ++i) {
            blocks.push_back(noise::PerlinNoise::fromRandom(random));
        }
    }
    return blocks;
}

// --- the three noises in play -----------------------------------------------

struct ClimateNoises {
    density::NoiseParameters offset;
    density::NoiseParameters temperature;
    density::NoiseParameters vegetation;
    Layout offsetLayout;
    Layout temperatureLayout;
    Layout vegetationLayout;
};

constexpr std::string_view kOffsetId = "minecraft:offset";
constexpr std::string_view kTemperatureId = "minecraft:temperature";
constexpr std::string_view kVegetationId = "minecraft:vegetation";

[[nodiscard]] density::NoiseParameters parametersOf(const data::Pack& pack, std::string_view id) {
    const data::ResourceLocation location = data::ResourceLocation::parse(id);
    const data::PackEntry* entry = pack.find(data::Registry::Noise, location);
    if (entry == nullptr) {
        std::fprintf(stderr, "the pack does not define worldgen/noise %s\n",
                     std::string{id}.c_str());
        std::exit(1);
    }
    return density::NoiseParameters::fromJson(entry->json, location);
}

[[nodiscard]] ClimateNoises climateNoisesOf(const data::Pack& pack) {
    ClimateNoises noises;
    noises.offset = parametersOf(pack, kOffsetId);
    noises.temperature = parametersOf(pack, kTemperatureId);
    noises.vegetation = parametersOf(pack, kVegetationId);
    noises.offsetLayout = layoutFor(noises.offset);
    noises.temperatureLayout = layoutFor(noises.temperature);
    noises.vegetationLayout = layoutFor(noises.vegetation);
    return noises;
}

// --- scoring ----------------------------------------------------------------

struct Tally {
    std::size_t cells = 0;
    std::size_t agree = 0;
    std::size_t interiorCells = 0;
    std::size_t interiorAgree = 0;
    std::vector<std::size_t> vanillaCounts;
    std::vector<std::size_t> ourCounts;

    explicit Tally(std::size_t biomes) : vanillaCounts(biomes, 0), ourCounts(biomes, 0) {}

    void add(std::uint16_t vanilla, std::uint16_t ours, bool boundary) {
        ++cells;
        ++vanillaCounts[vanilla];
        ++ourCounts[ours];
        const bool same = vanilla == ours;
        if (same) {
            ++agree;
        }
        if (!boundary) {
            ++interiorCells;
            if (same) {
                ++interiorAgree;
            }
        }
    }

    void absorb(const Tally& other) {
        cells += other.cells;
        agree += other.agree;
        interiorCells += other.interiorCells;
        interiorAgree += other.interiorAgree;
        for (std::size_t i = 0; i < vanillaCounts.size(); ++i) {
            vanillaCounts[i] += other.vanillaCounts[i];
            ourCounts[i] += other.ourCounts[i];
        }
    }

    [[nodiscard]] double rate() const {
        return cells == 0 ? 0.0 : static_cast<double>(agree) / static_cast<double>(cells);
    }

    /// The agreement two INDEPENDENT labelings with these marginals would
    /// reach. A bare percentage over five unequal biomes says nothing without
    /// it.
    [[nodiscard]] double chanceBaseline() const {
        if (cells == 0) {
            return 0.0;
        }
        double sum = 0.0;
        for (std::size_t i = 0; i < vanillaCounts.size(); ++i) {
            sum += (static_cast<double>(vanillaCounts[i]) / static_cast<double>(cells)) *
                   (static_cast<double>(ourCounts[i]) / static_cast<double>(cells));
        }
        return sum;
    }
};

/// Scores one candidate (seed rule, block offset) over one world.
[[nodiscard]] Tally scoreCandidate(const ClimateNoises& noises, const biome::ParameterList& table,
                                   const BiomeIndex& biomes, const World& world,
                                   const std::vector<noise::PerlinNoise>& offsetBlocks,
                                   const std::vector<noise::PerlinNoise>& temperatureBlocks,
                                   const std::vector<noise::PerlinNoise>& vegetationBlocks,
                                   std::size_t block) {
    Tally tally{biomes.size()};
    const auto offset = [&](double x, double y, double z) {
        return sampleNormal(noises.offsetLayout, offsetBlocks, block, x, y, z);
    };
    const auto temperature = [&](double x, double y, double z) {
        return sampleNormal(noises.temperatureLayout, temperatureBlocks, block, x, y, z);
    };
    const auto vegetation = [&](double x, double y, double z) {
        return sampleNormal(noises.vegetationLayout, vegetationBlocks, block, x, y, z);
    };
    for (const Cell& cell : world.cells) {
        const Climate climate = climateAt(offset, temperature, vegetation,
                                          static_cast<double>(cell.x), static_cast<double>(cell.z));
        const std::optional<std::uint16_t> chosen =
            biomes.find(table.find(sampleOf(climate)).toString());
        tally.add(cell.biome, chosen.value_or(0), cell.boundary);
    }
    return tally;
}

struct Result {
    std::size_t seedRule = 0;
    std::size_t block = 0;
    std::size_t agreed = 0;
};

} // namespace

// NOLINTNEXTLINE(bugprone-exception-escape): a throw here is a fixture fault
// and the message is the point; there is nothing to recover to.
int main(int argc, char** argv) {
    if (argc < 3) {
        std::fprintf(stderr,
                     "usage: %s <fixtures-dir> "
                     "--preset|--control|--model|--modern|--boundary|--scan|"
                     "--candidate <rule> <block>\n",
                     argv[0]);
        return 2;
    }
    const std::filesystem::path fixtures{argv[1]};
    const std::string mode{argv[2]};

    const std::filesystem::path tree = findWorldgenTree(fixtures);
    const std::filesystem::path netherTable =
        findUnder(fixtures, "nether.json", "biome_parameters");
    const std::filesystem::path overworldTable =
        findUnder(fixtures, "overworld.json", "biome_parameters");
    if (tree.empty() || netherTable.empty() || overworldTable.empty()) {
        std::fprintf(stderr,
                     "no extracted vanilla worldgen or biome_parameters under %s — Mojang-derived "
                     "and never committed (SPEC §12). Generate them with: tools/fetch-vanilla\n",
                     fixtures.string().c_str());
        return 77;
    }

    const auto readTable = [](const std::filesystem::path& path, std::string_view id) {
        std::ifstream stream(path);
        return biome::ParameterList::fromJson(nlohmann::json::parse(stream),
                                              data::ResourceLocation::parse(id));
    };
    const biome::ParameterList nether = readTable(netherTable, "minecraft:nether");
    const BiomeIndex biomes{nether};

    if (mode == "--preset") {
        std::printf("nether multi_noise parameter list: %zu entries, from the server's own data "
                    "generator (--reports), kept at %s\n",
                    nether.size(), netherTable.string().c_str());
        std::printf("  the pack ships only {\"preset\": \"minecraft:nether\"}; these numbers are "
                    "OBSERVED SERVER OUTPUT, not read out of the jar\n");
        for (const auto& entry : nether.entries()) {
            const auto& p = entry.parameters;
            std::printf("  %-28s T[%+.4f,%+.4f] H[%+.4f,%+.4f] C[%+.4f,%+.4f] E[%+.4f,%+.4f] "
                        "D[%+.4f,%+.4f] W[%+.4f,%+.4f] offset %+.4f\n",
                        entry.biome.toString().c_str(), p.temperature.min, p.temperature.max,
                        p.humidity.min, p.humidity.max, p.continentalness.min,
                        p.continentalness.max, p.erosion.min, p.erosion.max, p.depth.min,
                        p.depth.max, p.weirdness.min, p.weirdness.max, p.offset);
        }
        return 0;
    }

    const data::Pack pack = data::Pack::open(tree);
    stratum::settings::LoadedSettings loaded = stratum::settings::loadAll(pack);
    const auto& netherSettings =
        loaded.settings.at(data::ResourceLocation::parse("minecraft:nether"));
    const ClimateNoises noises = climateNoisesOf(pack);

    // The noises the Nether's climate actually reaches, from the library's own
    // graph walk rather than from this file's idea of the router.
    std::vector<data::ResourceLocation> wanted = loaded.graph.noisesReachableFrom(
        netherSettings.router.at(stratum::settings::RouterEntry::Temperature));
    for (const auto& id : loaded.graph.noisesReachableFrom(
             netherSettings.router.at(stratum::settings::RouterEntry::Vegetation))) {
        if (std::find(wanted.begin(), wanted.end(), id) == wanted.end()) {
            wanted.push_back(id);
        }
    }

    // --- the decoder control, on the overworld ------------------------------
    //
    // THREE ARMS, because two are not enough. The positive arm says the
    // decoder can see a correct seeding. The negative arm says a WRONG seeding
    // does not survive it. And the third arm is what makes the second
    // readable: a wrong seeding is not a random relabeling of the map, because
    // both arms share the coordinates, the y structure and vanilla's own biome
    // marginals, so the null for "a different world's labels against this
    // world's" sits well above the null for "two independent draws". That null
    // is measured rather than modelled, by scoring vanilla's OWN goldens at one
    // seed against vanilla's own goldens at another, at matching coordinates —
    // two real worlds, every shared structure intact, nothing in common but
    // the geometry.
    if (mode == "--control") {
        const biome::ParameterList overworld = readTable(overworldTable, "minecraft:overworld");
        const auto& settings =
            loaded.settings.at(data::ResourceLocation::parse("minecraft:overworld"));
        // EVERY FOURTH CHUNK OF THE WHOLE REGION, not a corner of it, and the
        // distinction is the one the Nether case already had to learn: over a
        // 32x32-block corner a world is essentially one biome, so "agreement"
        // there measures whether two maps happen to share a dominant biome and
        // the effective sample size is the number of REGIONS, not the number of
        // cells. Measured: at a 2x2-chunk corner the wrong-seed arm scored
        // 10.56% against a 3.87% cross-world null and looked like a control
        // failure, which was the sampling and not the decoder.
        constexpr std::int32_t kChunkStride = 4;
        // Four heights rather than every section: the overworld's biome does
        // vary down a column — that is what `depth` is for — so the sample has
        // to span y, but 24 sections a chunk buys correlated cells at 24 times
        // the cost.
        constexpr std::array<std::int32_t, 4> kHeights{-48, 16, 64, 112};

        // Per seed, the stored labels in one fixed coordinate order, so the
        // cross-world arm can pair them up cell for cell.
        std::vector<std::vector<std::string>> goldenPerSeed;
        std::size_t cells = 0;
        std::size_t positive = 0;
        std::size_t negative = 0;
        // Keyed by seed and horizontal position, not counted: the residual
        // below turns out to be whole COLUMNS that disagree at every height,
        // and a count of cells would report each of them four times.
        std::map<std::string, std::string> misses;
        for (const std::int64_t seed : kAllSeeds) {
            const std::filesystem::path region = regionOf(fixtures, seed, "overworld");
            if (region.empty()) {
                continue;
            }
            const auto build = [&](std::int64_t with) {
                return density::NoiseRegistry::create(pack, loaded.graph.referencedNoises(), with,
                                                      density::RandomSource::Xoroshiro);
            };
            const auto right = build(seed);
            const auto wrong = build(seed + 1);
            const density::CellGeometry geometry{.width = settings.geometry.cellWidth(),
                                                 .height = settings.geometry.cellHeight()};
            const density::Interpreter rightInterpreter(loaded.graph, right, geometry);
            const density::Interpreter wrongInterpreter(loaded.graph, wrong, geometry);
            const region::RegionFile file = region::RegionFile::open(region);
            std::vector<std::string> golden;
            for (std::int32_t chunkZ = 0; chunkZ < region::kChunksPerAxis; chunkZ += kChunkStride) {
                for (std::int32_t chunkX = 0; chunkX < region::kChunksPerAxis;
                     chunkX += kChunkStride) {
                    if (!file.hasChunk(chunkX, chunkZ)) {
                        continue;
                    }
                    const chunk::Chunk decoded =
                        chunk::Chunk::decode(nbt::read(file.readChunk(chunkX, chunkZ)).root);
                    for (const auto& section : decoded.sections()) {
                        if (section.biomes.empty()) {
                            continue;
                        }
                        for (int cellY = 0; cellY < 4; ++cellY) {
                            const std::int32_t y = (section.y * 16) + (cellY * 4);
                            if (std::find(kHeights.begin(), kHeights.end(), y) == kHeights.end()) {
                                continue;
                            }
                            for (int cellZ = 0; cellZ < 4; ++cellZ) {
                                for (int cellX = 0; cellX < 4; ++cellX) {
                                    const std::size_t index =
                                        (static_cast<std::size_t>(cellY) * 16U) +
                                        (static_cast<std::size_t>(cellZ) * 4U) +
                                        static_cast<std::size_t>(cellX);
                                    if (index >= section.biomes.size()) {
                                        continue;
                                    }
                                    const std::string& stored =
                                        section.biomePalette[section.biomes[index]];
                                    const density::Point at{.x = (chunkX * 16) + (cellX * 4),
                                                            .y = y,
                                                            .z = (chunkZ * 16) + (cellZ * 4)};
                                    const auto evaluate = [&](const density::Interpreter& with) {
                                        using stratum::settings::RouterEntry;
                                        return biome::ClimateSample{
                                            .temperature = with.evaluate(
                                                settings.router.at(RouterEntry::Temperature), at),
                                            .humidity = with.evaluate(
                                                settings.router.at(RouterEntry::Vegetation), at),
                                            .continentalness = with.evaluate(
                                                settings.router.at(RouterEntry::Continents), at),
                                            .erosion = with.evaluate(
                                                settings.router.at(RouterEntry::Erosion), at),
                                            .depth = with.evaluate(
                                                settings.router.at(RouterEntry::Depth), at),
                                            .weirdness = with.evaluate(
                                                settings.router.at(RouterEntry::Ridges), at)};
                                    };
                                    ++cells;
                                    const std::string chosen =
                                        overworld.find(evaluate(rightInterpreter)).toString();
                                    if (chosen == stored) {
                                        ++positive;
                                    } else {
                                        std::string where = std::to_string(seed);
                                        where.append(" (").append(std::to_string(at.x));
                                        where.append(",").append(std::to_string(at.z));
                                        where.append(")");
                                        std::string what = stored;
                                        what.append(" -> ").append(chosen);
                                        misses[where] = what;
                                    }
                                    if (overworld.find(evaluate(wrongInterpreter)).toString() ==
                                        stored) {
                                        ++negative;
                                    }
                                    golden.push_back(stored);
                                }
                            }
                        }
                    }
                }
            }
            goldenPerSeed.push_back(std::move(golden));
        }
        if (goldenPerSeed.empty() || cells == 0) {
            std::fprintf(stderr, "no golden overworld regions under %s\n",
                         fixtures.string().c_str());
            return 77;
        }

        // The null: vanilla's own map at one seed against vanilla's own map at
        // another, cell for cell, over every pair of distinct worlds.
        std::size_t pairCells = 0;
        std::size_t pairAgree = 0;
        std::size_t pairs = 0;
        for (std::size_t a = 0; a < goldenPerSeed.size(); ++a) {
            for (std::size_t b = a + 1; b < goldenPerSeed.size(); ++b) {
                if (goldenPerSeed[a].size() != goldenPerSeed[b].size()) {
                    continue;
                }
                ++pairs;
                for (std::size_t i = 0; i < goldenPerSeed[a].size(); ++i) {
                    ++pairCells;
                    if (goldenPerSeed[a][i] == goldenPerSeed[b][i]) {
                        ++pairAgree;
                    }
                }
            }
        }
        const double positiveRate = static_cast<double>(positive) / static_cast<double>(cells);
        const double negativeRate = static_cast<double>(negative) / static_cast<double>(cells);
        const double nullRate =
            pairCells == 0 ? 0.0 : static_cast<double>(pairAgree) / static_cast<double>(pairCells);
        std::printf("control (overworld, %zu regions, %zu cells)\n", goldenPerSeed.size(), cells);
        std::printf("  worldSeed        %zu/%zu = %.4f%%\n", positive, cells, 100.0 * positiveRate);
        std::printf("  worldSeed + 1    %zu/%zu = %.4f%%\n", negative, cells, 100.0 * negativeRate);
        std::printf("  null (vanilla vs vanilla, %zu world pairs)  %zu/%zu = %.4f%%\n", pairs,
                    pairAgree, pairCells, 100.0 * nullRate);
        std::printf("  the positive arm's residual is %zu column(s), each wrong at every "
                    "sampled height — a horizontal disagreement, not a depth one:\n",
                    misses.size());
        for (const auto& [where, what] : misses) {
            std::printf("    seed %-40s %s\n", where.c_str(), what.c_str());
        }
        // The positive arm has to be EXACT, and the negative arm has to sit at
        // the null a genuinely unrelated world reaches. Neither alone is a
        // control: without the first, "no survivor" says the decoder is blind;
        // without the second, it says the decoder accepts anything.
        // NOT "== cells", and the difference is a finding rather than a
        // slackened threshold. The [biome] conformance cases report the
        // overworld biome source as EXACT, and over their sample it is: a
        // 64x64-block corner of four regions, 98304 cells, no miss. Spread the
        // same decode over the whole 512x512 of eight regions and five columns
        // out of 8192 come back wrong — 0.061% of cells, each of them wrong at
        // every sampled height, so a horizontal disagreement and not a depth
        // one. That is a residual of the biome source, not of this readback,
        // and it is named here with its seeds and coordinates rather than
        // rounded away. It is far too small to matter to what follows: the
        // separation this control has to establish is 99.94% against 6.37%.
        if (positiveRate < 0.999) {
            std::fprintf(stderr,
                         "control FAILED: the decoder recovers the modern seeding on its own "
                         "goldens at only %.4f%%\n",
                         100.0 * positiveRate);
            return 1;
        }
        if (negativeRate > nullRate + 0.02) {
            std::fprintf(stderr,
                         "control FAILED: the decoder scores worldSeed + 1 at %.4f%%, above the "
                         "%.4f%% an unrelated vanilla world reaches, so something other than the "
                         "seeding is doing the work\n",
                         100.0 * negativeRate, 100.0 * nullRate);
            return 1;
        }
        std::printf("control passed: this decoder recovers a correct seeding at %.4f%% and puts a "
                    "wrong one at the null (%.4f%% against the %.4f%% an unrelated vanilla world "
                    "reaches)\n",
                    100.0 * positiveRate, 100.0 * negativeRate, 100.0 * nullRate);
        return 0;
    }

    // --- the forward-model control, on the Nether ---------------------------
    if (mode == "--model") {
        constexpr std::int64_t kSeed = 42;
        const auto registry =
            density::NoiseRegistry::create(pack, wanted, kSeed, density::RandomSource::Xoroshiro);
        const density::Interpreter interpreter(
            loaded.graph, registry,
            density::CellGeometry{.width = netherSettings.geometry.cellWidth(),
                                  .height = netherSettings.geometry.cellHeight()});
        const auto& libraryOffset = registry.get(data::ResourceLocation::parse(kOffsetId));
        const auto& libraryTemperature =
            registry.get(data::ResourceLocation::parse(kTemperatureId));
        const auto& libraryVegetation = registry.get(data::ResourceLocation::parse(kVegetationId));
        const auto offsetBlocks = modernBlocksFor(noises.offset, kOffsetId, kSeed);
        const auto temperatureBlocks = modernBlocksFor(noises.temperature, kTemperatureId, kSeed);
        const auto vegetationBlocks = modernBlocksFor(noises.vegetation, kVegetationId, kSeed);

        std::size_t points = 0;
        std::size_t stackIdentical = 0;
        std::size_t chainIdentical = 0;
        std::size_t wholeIdentical = 0;
        const auto bits = [](double value) { return std::bit_cast<std::uint64_t>(value); };
        for (std::int32_t z = 0; z < 512; z += 16) {
            for (std::int32_t x = 0; x < 512; x += 16) {
                const auto fx = static_cast<double>(x);
                const auto fz = static_cast<double>(z);
                ++points;

                // stack: this file's sampleNormal against the library's
                // NormalNoise, for all three noises, at a point each of them
                // is actually read at.
                const bool stackOk =
                    bits(sampleNormal(noises.offsetLayout, offsetBlocks, 0, fx * 0.25, 0.0,
                                      fz * 0.25)) ==
                        bits(libraryOffset.sample(fx * 0.25, 0.0, fz * 0.25)) &&
                    bits(sampleNormal(noises.temperatureLayout, temperatureBlocks, 0, fx * 0.25,
                                      0.0, fz * 0.25)) ==
                        bits(libraryTemperature.sample(fx * 0.25, 0.0, fz * 0.25)) &&
                    bits(sampleNormal(noises.vegetationLayout, vegetationBlocks, 0, fx * 0.25, 0.0,
                                      fz * 0.25)) ==
                        bits(libraryVegetation.sample(fx * 0.25, 0.0, fz * 0.25));
                if (stackOk) {
                    ++stackIdentical;
                }

                const density::Point at{.x = x, .y = kNetherSampleY, .z = z};
                using stratum::settings::RouterEntry;
                const double routerTemperature =
                    interpreter.evaluate(netherSettings.router.at(RouterEntry::Temperature), at);
                const double routerVegetation =
                    interpreter.evaluate(netherSettings.router.at(RouterEntry::Vegetation), at);

                // chain: this file's shift/shifted_noise wiring over the
                // LIBRARY's noises, against the Interpreter's own evaluation.
                const Climate viaLibrary = climateAt(
                    [&](double a, double b, double c) { return libraryOffset.sample(a, b, c); },
                    [&](double a, double b, double c) {
                        return libraryTemperature.sample(a, b, c);
                    },
                    [&](double a, double b, double c) { return libraryVegetation.sample(a, b, c); },
                    fx, fz);
                if (bits(viaLibrary.temperature) == bits(routerTemperature) &&
                    bits(viaLibrary.vegetation) == bits(routerVegetation)) {
                    ++chainIdentical;
                }

                // whole: the composition — this file's chain over this file's
                // stacks, which is exactly what the scan runs.
                const Climate viaModel = climateAt(
                    [&](double a, double b, double c) {
                        return sampleNormal(noises.offsetLayout, offsetBlocks, 0, a, b, c);
                    },
                    [&](double a, double b, double c) {
                        return sampleNormal(noises.temperatureLayout, temperatureBlocks, 0, a, b,
                                            c);
                    },
                    [&](double a, double b, double c) {
                        return sampleNormal(noises.vegetationLayout, vegetationBlocks, 0, a, b, c);
                    },
                    fx, fz);
                if (bits(viaModel.temperature) == bits(routerTemperature) &&
                    bits(viaModel.vegetation) == bits(routerVegetation)) {
                    ++wholeIdentical;
                }
            }
        }
        std::printf("forward model at seed 42, %zu points\n", points);
        std::printf("  stack (sampleNormal vs NormalNoise, 3 noises)  %zu/%zu\n", stackIdentical,
                    points);
        std::printf("  chain (shift wiring vs Interpreter)            %zu/%zu\n", chainIdentical,
                    points);
        std::printf("  whole (what the scan runs vs Interpreter)      %zu/%zu\n", wholeIdentical,
                    points);
        if (stackIdentical != points || chainIdentical != points || wholeIdentical != points) {
            std::fprintf(stderr, "forward model FAILED: the scan's model is not the function the "
                                 "library computes, so its null and its scores are about "
                                 "something else\n");
            return 1;
        }
        std::printf("forward model passed\n");
        return 0;
    }

    // --- everything below reads the Nether goldens --------------------------
    const auto loadWorlds = [&](std::span<const std::int64_t> seeds, std::int32_t stride) {
        std::vector<World> worlds;
        for (const std::int64_t seed : seeds) {
            const std::filesystem::path region = regionOf(fixtures, seed, "nether");
            if (region.empty()) {
                continue;
            }
            worlds.push_back(readNetherWorld(region, seed, biomes, stride));
        }
        return worlds;
    };

    if (mode == "--modern") {
        // The number already on record: 8873/32768 = 27.08% against a 30.23%
        // baseline, over ALL EIGHT seeds, which is how
        // vanilla_legacy_nether_climate_gap_test.cpp measured it. Reproduced
        // here through THIS file's chain rather than through the Interpreter,
        // so that agreeing with it is evidence about this file.
        const std::vector<World> worlds = loadWorlds(kAllSeeds, kNetherChunkStride);
        if (worlds.empty()) {
            std::fprintf(stderr, "no golden nether regions under %s\n", fixtures.string().c_str());
            return 77;
        }
        Tally overall{biomes.size()};
        std::size_t varying = 0;
        for (const World& world : worlds) {
            varying += world.varyingWithY;
            const auto offsetBlocks = modernBlocksFor(noises.offset, kOffsetId, world.seed);
            const auto temperatureBlocks =
                modernBlocksFor(noises.temperature, kTemperatureId, world.seed);
            const auto vegetationBlocks =
                modernBlocksFor(noises.vegetation, kVegetationId, world.seed);
            const Tally tally = scoreCandidate(noises, nether, biomes, world, offsetBlocks,
                                               temperatureBlocks, vegetationBlocks, 0);
            std::printf("  seed %-21lld %5zu/%5zu = %6.2f%%  baseline %6.2f%%\n",
                        static_cast<long long>(world.seed), tally.agree, tally.cells,
                        100.0 * tally.rate(), 100.0 * tally.chanceBaseline());
            overall.absorb(tally);
        }
        std::printf("modern derivation on the nether, %zu regions: %zu/%zu = %.2f%%, chance "
                    "baseline %.2f%%; %zu column(s) varying with y\n",
                    worlds.size(), overall.agree, overall.cells, 100.0 * overall.rate(),
                    100.0 * overall.chanceBaseline(), varying);
        for (std::size_t i = 0; i < biomes.size(); ++i) {
            std::printf("    %-28s vanilla %6zu, modern rule %6zu\n",
                        biomes.nameOf(static_cast<std::uint16_t>(i)).c_str(),
                        overall.vanillaCounts[i], overall.ourCounts[i]);
        }
        return 0;
    }

    if (mode == "--boundary") {
        const std::vector<World> worlds = loadWorlds(kDistinctSeeds, kNetherChunkStride);
        if (worlds.empty()) {
            std::fprintf(stderr, "no golden nether regions under %s\n", fixtures.string().c_str());
            return 77;
        }
        std::size_t cells = 0;
        std::size_t boundary = 0;
        std::vector<std::size_t> counts(biomes.size(), 0);
        for (const World& world : worlds) {
            for (const Cell& cell : world.cells) {
                ++cells;
                ++counts[cell.biome];
                if (cell.boundary) {
                    ++boundary;
                }
            }
        }
        std::printf("denominator: %zu cells over %zu independent worlds\n", cells, worlds.size());
        std::printf("  boundary-adjacent (a 4-neighbour inside the same chunk carries a "
                    "different biome): %zu (%.2f%%)\n",
                    boundary, 100.0 * static_cast<double>(boundary) / static_cast<double>(cells));
        std::printf("  interior: %zu (%.2f%%)\n", cells - boundary,
                    100.0 * static_cast<double>(cells - boundary) / static_cast<double>(cells));
        double selfAgreement = 0.0;
        for (std::size_t i = 0; i < biomes.size(); ++i) {
            const double share = static_cast<double>(counts[i]) / static_cast<double>(cells);
            selfAgreement += share * share;
            std::printf("    %-28s %6zu (%5.2f%%)\n",
                        biomes.nameOf(static_cast<std::uint16_t>(i)).c_str(), counts[i],
                        100.0 * share);
        }
        std::printf("  a labeling drawn independently WITH VANILLA'S OWN MARGINALS would agree "
                    "%.2f%% of the time — that is the ceiling on what a wrong seeding has to "
                    "beat, and the floor under every number this readback prints\n",
                    100.0 * selfAgreement);
        return 0;
    }

    const bool candidateMode = mode == "--candidate";
    if (!candidateMode && mode != "--scan") {
        std::fprintf(stderr, "unknown mode %s\n", mode.c_str());
        return 2;
    }

    // Stage 1 subsamples chunks hard: the full stride-2 sample is 4096 cells a
    // world and 270,000 candidates over it is not a run anyone would finish.
    // Stage 2 re-scores the survivors over the full sample, so the reported
    // number for anything that matters has the full denominator.
    constexpr std::int32_t kScanStride = 8;
    const std::vector<World> coarse = loadWorlds(kDistinctSeeds, kScanStride);
    if (coarse.empty()) {
        std::fprintf(stderr, "no golden nether regions under %s\n", fixtures.string().c_str());
        return 77;
    }
    std::size_t coarseCells = 0;
    for (const World& world : coarse) {
        coarseCells += world.cells.size();
    }

    const std::size_t blocksNeeded =
        kBlockOffsets +
        std::max({noises.offsetLayout.blocksPerNoise, noises.temperatureLayout.blocksPerNoise,
                  noises.vegetationLayout.blocksPerNoise});

    if (candidateMode) {
        if (argc < 5) {
            std::fprintf(stderr, "--candidate needs a rule index and a block offset\n");
            return 2;
        }
        const auto ruleIndex = static_cast<std::size_t>(std::strtoull(argv[3], nullptr, 10));
        const auto block = static_cast<std::size_t>(std::strtoull(argv[4], nullptr, 10));
        if (ruleIndex >= kSeedRules || block >= kBlockOffsets) {
            std::fprintf(stderr, "rule must be < %zu and block < %zu\n", kSeedRules, kBlockOffsets);
            return 2;
        }
        const SeedRule rule = ruleAt(ruleIndex);
        const std::vector<World> full = loadWorlds(kDistinctSeeds, kNetherChunkStride);
        Tally overall{biomes.size()};
        for (const World& world : full) {
            const auto offsetBlocks =
                blocksFor(rule, seedFor(rule, world.seed, kOffsetId), blocksNeeded);
            const auto temperatureBlocks =
                blocksFor(rule, seedFor(rule, world.seed, kTemperatureId), blocksNeeded);
            const auto vegetationBlocks =
                blocksFor(rule, seedFor(rule, world.seed, kVegetationId), blocksNeeded);
            overall.absorb(scoreCandidate(noises, nether, biomes, world, offsetBlocks,
                                          temperatureBlocks, vegetationBlocks, block));
        }
        std::printf("rule %zu block %zu (%s): %zu/%zu = %.2f%%, chance baseline %.2f%%; "
                    "interior only %zu/%zu = %.2f%%\n",
                    ruleIndex, block, describe(rule).c_str(), overall.agree, overall.cells,
                    100.0 * overall.rate(), 100.0 * overall.chanceBaseline(), overall.interiorAgree,
                    overall.interiorCells,
                    overall.interiorCells == 0
                        ? 0.0
                        : 100.0 * static_cast<double>(overall.interiorAgree) /
                              static_cast<double>(overall.interiorCells));
        return 0;
    }

    // --- the scan -----------------------------------------------------------
    std::printf("candidate space: %zu seed rules x %zu block offsets = %zu candidates\n",
                kSeedRules, kBlockOffsets, kSeedRules * kBlockOffsets);
    std::printf("stage 1 over %zu cells (%zu worlds, chunk stride %d)\n", coarseCells,
                coarse.size(), kScanStride);

    std::vector<Result> best;
    std::vector<std::size_t> histogram(coarseCells + 1, 0);
    constexpr std::size_t kKeep = 32;
    for (std::size_t ruleIndex = 0; ruleIndex < kSeedRules; ++ruleIndex) {
        const SeedRule rule = ruleAt(ruleIndex);
        std::vector<std::vector<noise::PerlinNoise>> offsetBlocks;
        std::vector<std::vector<noise::PerlinNoise>> temperatureBlocks;
        std::vector<std::vector<noise::PerlinNoise>> vegetationBlocks;
        offsetBlocks.reserve(coarse.size());
        temperatureBlocks.reserve(coarse.size());
        vegetationBlocks.reserve(coarse.size());
        for (const World& world : coarse) {
            offsetBlocks.push_back(
                blocksFor(rule, seedFor(rule, world.seed, kOffsetId), blocksNeeded));
            temperatureBlocks.push_back(
                blocksFor(rule, seedFor(rule, world.seed, kTemperatureId), blocksNeeded));
            vegetationBlocks.push_back(
                blocksFor(rule, seedFor(rule, world.seed, kVegetationId), blocksNeeded));
        }
        for (std::size_t block = 0; block < kBlockOffsets; ++block) {
            std::size_t agreed = 0;
            for (std::size_t w = 0; w < coarse.size(); ++w) {
                agreed += scoreCandidate(noises, nether, biomes, coarse[w], offsetBlocks[w],
                                         temperatureBlocks[w], vegetationBlocks[w], block)
                              .agree;
            }
            ++histogram[agreed];
            if (best.size() < kKeep || agreed > best.back().agreed) {
                best.push_back({ruleIndex, block, agreed});
                std::sort(best.begin(), best.end(),
                          [](const Result& a, const Result& b) { return a.agreed > b.agreed; });
                if (best.size() > kKeep) {
                    best.resize(kKeep);
                }
            }
        }
        if ((ruleIndex % 100) == 99) {
            std::printf("  ... %zu/%zu rules\n", ruleIndex + 1, kSeedRules);
            std::fflush(stdout);
        }
    }

    std::size_t total = 0;
    std::size_t sum = 0;
    std::size_t worst = 0;
    for (std::size_t i = 0; i < histogram.size(); ++i) {
        total += histogram[i];
        sum += histogram[i] * i;
        if (histogram[i] != 0) {
            worst = i;
        }
    }
    const double mean = total == 0 ? 0.0 : static_cast<double>(sum) / static_cast<double>(total);
    double variance = 0.0;
    for (std::size_t i = 0; i < histogram.size(); ++i) {
        const double delta = static_cast<double>(i) - mean;
        variance += static_cast<double>(histogram[i]) * delta * delta;
    }
    variance = total == 0 ? 0.0 : variance / static_cast<double>(total);

    // THE NULL IS MEASURED, NOT ASSUMED: every candidate in the space is
    // wrong, so their agreement counts ARE the null distribution.
    std::printf("null over %zu scored candidates: mean %.2f/%zu (%.2f%%), sd %.2f, max %zu/%zu "
                "(%.2f%%)\n",
                total, mean, coarseCells, 100.0 * mean / static_cast<double>(coarseCells),
                std::sqrt(variance), worst, coarseCells,
                100.0 * static_cast<double>(worst) / static_cast<double>(coarseCells));

    // The rank distribution, not just its two ends: a maximum quoted without
    // the shape underneath it is how a score at the null reads as an outlier.
    const auto quantile = [&](double fraction) {
        const auto target = static_cast<std::size_t>(fraction * static_cast<double>(total));
        std::size_t seen = 0;
        for (std::size_t i = 0; i < histogram.size(); ++i) {
            seen += histogram[i];
            if (seen >= target) {
                return i;
            }
        }
        return histogram.size() - 1;
    };
    std::printf("  rank distribution: p50 %zu (%.2f%%), p90 %zu (%.2f%%), p99 %zu (%.2f%%), "
                "p99.9 %zu (%.2f%%)\n",
                quantile(0.50),
                100.0 * static_cast<double>(quantile(0.50)) / static_cast<double>(coarseCells),
                quantile(0.90),
                100.0 * static_cast<double>(quantile(0.90)) / static_cast<double>(coarseCells),
                quantile(0.99),
                100.0 * static_cast<double>(quantile(0.99)) / static_cast<double>(coarseCells),
                quantile(0.999),
                100.0 * static_cast<double>(quantile(0.999)) / static_cast<double>(coarseCells));

    // The modern rule through the SAME cells, as a reference point rather than
    // a candidate: it is known wrong for a legacy dimension, so where it lands
    // says what "wrong" looks like on this sample.
    std::size_t modernAgreed = 0;
    for (const World& world : coarse) {
        modernAgreed +=
            scoreCandidate(noises, nether, biomes, world,
                           modernBlocksFor(noises.offset, kOffsetId, world.seed),
                           modernBlocksFor(noises.temperature, kTemperatureId, world.seed),
                           modernBlocksFor(noises.vegetation, kVegetationId, world.seed), 0)
                .agree;
    }
    std::printf("  for reference, the MODERN rule on these same cells: %zu/%zu (%.2f%%)\n",
                modernAgreed, coarseCells,
                100.0 * static_cast<double>(modernAgreed) / static_cast<double>(coarseCells));

    std::printf("stage 1 top %zu:\n", best.size());
    for (std::size_t i = 0; i < best.size(); ++i) {
        std::printf("  #%2zu rule %3zu block %3zu: %zu/%zu (%.2f%%)  %s\n", i + 1, best[i].seedRule,
                    best[i].block, best[i].agreed, coarseCells,
                    100.0 * static_cast<double>(best[i].agreed) / static_cast<double>(coarseCells),
                    describe(ruleAt(best[i].seedRule)).c_str());
    }

    // Stage 2: the survivors over the FULL sample, so nothing is reported at a
    // denominator smaller than the oracle actually offers.
    const std::vector<World> full = loadWorlds(kDistinctSeeds, kNetherChunkStride);
    std::printf("stage 2, full sample:\n");
    std::size_t fullCells = 0;
    for (const World& world : full) {
        fullCells += world.cells.size();
    }
    double bestRate = 0.0;
    for (const Result& result : best) {
        const SeedRule rule = ruleAt(result.seedRule);
        Tally overall{biomes.size()};
        for (const World& world : full) {
            const auto offsetBlocks =
                blocksFor(rule, seedFor(rule, world.seed, kOffsetId), blocksNeeded);
            const auto temperatureBlocks =
                blocksFor(rule, seedFor(rule, world.seed, kTemperatureId), blocksNeeded);
            const auto vegetationBlocks =
                blocksFor(rule, seedFor(rule, world.seed, kVegetationId), blocksNeeded);
            overall.absorb(scoreCandidate(noises, nether, biomes, world, offsetBlocks,
                                          temperatureBlocks, vegetationBlocks, result.block));
        }
        bestRate = std::max(bestRate, overall.rate());
        std::printf(
            "  rule %3zu block %3zu: %zu/%zu (%.2f%%), baseline %.2f%%, interior "
            "%zu/%zu (%.2f%%)  %s\n",
            result.seedRule, result.block, overall.agree, overall.cells, 100.0 * overall.rate(),
            100.0 * overall.chanceBaseline(), overall.interiorAgree, overall.interiorCells,
            overall.interiorCells == 0 ? 0.0
                                       : 100.0 * static_cast<double>(overall.interiorAgree) /
                                             static_cast<double>(overall.interiorCells),
            describe(rule).c_str());
    }
    std::printf("full sample: %zu cells over %zu worlds; best survivor rate %.2f%%\n", fullCells,
                full.size(), 100.0 * bestRate);
    return 0;
}
